// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: checkins.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countCheckInsByIndicator = `-- name: CountCheckInsByIndicator :one
SELECT COUNT(*)
FROM checkins
WHERE org_id = $1
  AND indicator_id = $2
  AND deleted_at IS NULL
`

type CountCheckInsByIndicatorParams struct {
	OrgID       uuid.UUID
	IndicatorID uuid.UUID
}

func (q *Queries) CountCheckInsByIndicator(ctx context.Context, arg CountCheckInsByIndicatorParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCheckInsByIndicator, arg.OrgID, arg.IndicatorID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCheckIn = `-- name: CreateCheckIn :one
INSERT INTO checkins (id, org_id, indicator_id, author_id, value, previous_value, confidence, note, mentions)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, org_id, indicator_id, author_id, value, previous_value, confidence, note, mentions, created_at, updated_at
`

type CreateCheckInParams struct {
	ID            uuid.UUID
	OrgID         uuid.UUID
	IndicatorID   uuid.UUID
	AuthorID      uuid.UUID
	Value         string
	PreviousValue pgtype.Text
	Confidence    string
	Note          pgtype.Text
	Mentions      []string
}

type CreateCheckInRow struct {
	ID            uuid.UUID
	OrgID         uuid.UUID
	IndicatorID   uuid.UUID
	AuthorID      uuid.UUID
	Value         string
	PreviousValue pgtype.Text
	Confidence    string
	Note          pgtype.Text
	Mentions      []string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) CreateCheckIn(ctx context.Context, arg CreateCheckInParams) (CreateCheckInRow, error) {
	row := q.db.QueryRow(ctx, createCheckIn,
		arg.ID,
		arg.OrgID,
		arg.IndicatorID,
		arg.AuthorID,
		arg.Value,
		arg.PreviousValue,
		arg.Confidence,
		arg.Note,
		arg.Mentions,
	)
	var i CreateCheckInRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.IndicatorID,
		&i.AuthorID,
		&i.Value,
		&i.PreviousValue,
		&i.Confidence,
		&i.Note,
		&i.Mentions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCheckInByID = `-- name: GetCheckInByID :one
SELECT id, org_id, indicator_id, author_id, value, previous_value, confidence, note, mentions, created_at, updated_at
FROM checkins
WHERE id = $1
  AND org_id = $2
  AND deleted_at IS NULL
`

type GetCheckInByIDParams struct {
	ID    uuid.UUID
	OrgID uuid.UUID
}

type GetCheckInByIDRow struct {
	ID            uuid.UUID
	OrgID         uuid.UUID
	IndicatorID   uuid.UUID
	AuthorID      uuid.UUID
	Value         string
	PreviousValue pgtype.Text
	Confidence    string
	Note          pgtype.Text
	Mentions      []string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) GetCheckInByID(ctx context.Context, arg GetCheckInByIDParams) (GetCheckInByIDRow, error) {
	row := q.db.QueryRow(ctx, getCheckInByID, arg.ID, arg.OrgID)
	var i GetCheckInByIDRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.IndicatorID,
		&i.AuthorID,
		&i.Value,
		&i.PreviousValue,
		&i.Confidence,
		&i.Note,
		&i.Mentions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCheckInsByIndicator = `-- name: ListCheckInsByIndicator :many
SELECT
    ci.id, ci.org_id, ci.indicator_id, ci.author_id,
    ci.value, ci.previous_value, ci.confidence, ci.note, ci.mentions,
    ci.created_at, ci.updated_at,
    u.first_name AS author_first_name,
    u.last_name  AS author_last_name
FROM checkins ci
JOIN users u ON u.id = ci.author_id
WHERE ci.org_id = $1
  AND ci.indicator_id = $2
  AND ci.deleted_at IS NULL
ORDER BY ci.created_at DESC
LIMIT $3 OFFSET $4
`

type ListCheckInsByIndicatorParams struct {
	OrgID       uuid.UUID
	IndicatorID uuid.UUID
	Limit       int32
	Offset      int32
}

type ListCheckInsByIndicatorRow struct {
	ID              uuid.UUID
	OrgID           uuid.UUID
	IndicatorID     uuid.UUID
	AuthorID        uuid.UUID
	Value           string
	PreviousValue   pgtype.Text
	Confidence      string
	Note            pgtype.Text
	Mentions        []string
	CreatedAt       time.Time
	UpdatedAt       time.Time
	AuthorFirstName string
	AuthorLastName  string
}

func (q *Queries) ListCheckInsByIndicator(ctx context.Context, arg ListCheckInsByIndicatorParams) ([]ListCheckInsByIndicatorRow, error) {
	rows, err := q.db.Query(ctx, listCheckInsByIndicator,
		arg.OrgID,
		arg.IndicatorID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCheckInsByIndicatorRow
	for rows.Next() {
		var i ListCheckInsByIndicatorRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.IndicatorID,
			&i.AuthorID,
			&i.Value,
			&i.PreviousValue,
			&i.Confidence,
			&i.Note,
			&i.Mentions,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorFirstName,
			&i.AuthorLastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteCheckIn = `-- name: SoftDeleteCheckIn :exec
UPDATE checkins
SET deleted_at = NOW()
WHERE id = $1
  AND org_id = $2
  AND deleted_at IS NULL
`

type SoftDeleteCheckInParams struct {
	ID    uuid.UUID
	OrgID uuid.UUID
}

func (q *Queries) SoftDeleteCheckIn(ctx context.Context, arg SoftDeleteCheckInParams) error {
	_, err := q.db.Exec(ctx, softDeleteCheckIn, arg.ID, arg.OrgID)
	return err
}

const updateCheckIn = `-- name: UpdateCheckIn :one
UPDATE checkins
SET value          = $3,
    confidence     = $4,
    note           = $5,
    mentions       = $6,
    updated_at     = NOW()
WHERE id = $1
  AND org_id = $2
  AND deleted_at IS NULL
RETURNING id, org_id, indicator_id, author_id, value, previous_value, confidence, note, mentions, created_at, updated_at
`

type UpdateCheckInParams struct {
	ID         uuid.UUID
	OrgID      uuid.UUID
	Value      string
	Confidence string
	Note       pgtype.Text
	Mentions   []string
}

type UpdateCheckInRow struct {
	ID            uuid.UUID
	OrgID         uuid.UUID
	IndicatorID   uuid.UUID
	AuthorID      uuid.UUID
	Value         string
	PreviousValue pgtype.Text
	Confidence    string
	Note          pgtype.Text
	Mentions      []string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) UpdateCheckIn(ctx context.Context, arg UpdateCheckInParams) (UpdateCheckInRow, error) {
	row := q.db.QueryRow(ctx, updateCheckIn,
		arg.ID,
		arg.OrgID,
		arg.Value,
		arg.Confidence,
		arg.Note,
		arg.Mentions,
	)
	var i UpdateCheckInRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.IndicatorID,
		&i.AuthorID,
		&i.Value,
		&i.PreviousValue,
		&i.Confidence,
		&i.Note,
		&i.Mentions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
