// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cycles.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countCycles = `-- name: CountCycles :one
SELECT COUNT(*)
FROM cycles
WHERE organization_id = $1
  AND deleted_at IS NULL
`

func (q *Queries) CountCycles(ctx context.Context, organizationID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCycles, organizationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCyclesByStatus = `-- name: CountCyclesByStatus :one
SELECT COUNT(*)
FROM cycles
WHERE organization_id = $1
  AND status = $2
  AND deleted_at IS NULL
`

type CountCyclesByStatusParams struct {
	OrganizationID uuid.UUID
	Status         string
}

func (q *Queries) CountCyclesByStatus(ctx context.Context, arg CountCyclesByStatusParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCyclesByStatus, arg.OrganizationID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCycle = `-- name: CreateCycle :one
INSERT INTO cycles (id, organization_id, name, type, start_date, end_date, status, okr_definition_deadline, mid_review_date)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, organization_id, name, type, start_date, end_date, status, okr_definition_deadline, mid_review_date, created_at, updated_at
`

type CreateCycleParams struct {
	ID                    uuid.UUID
	OrganizationID        uuid.UUID
	Name                  string
	Type                  string
	StartDate             pgtype.Date
	EndDate               pgtype.Date
	Status                string
	OkrDefinitionDeadline pgtype.Date
	MidReviewDate         pgtype.Date
}

type CreateCycleRow struct {
	ID                    uuid.UUID
	OrganizationID        uuid.UUID
	Name                  string
	Type                  string
	StartDate             pgtype.Date
	EndDate               pgtype.Date
	Status                string
	OkrDefinitionDeadline pgtype.Date
	MidReviewDate         pgtype.Date
	CreatedAt             time.Time
	UpdatedAt             time.Time
}

func (q *Queries) CreateCycle(ctx context.Context, arg CreateCycleParams) (CreateCycleRow, error) {
	row := q.db.QueryRow(ctx, createCycle,
		arg.ID,
		arg.OrganizationID,
		arg.Name,
		arg.Type,
		arg.StartDate,
		arg.EndDate,
		arg.Status,
		arg.OkrDefinitionDeadline,
		arg.MidReviewDate,
	)
	var i CreateCycleRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Type,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.OkrDefinitionDeadline,
		&i.MidReviewDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCycleByID = `-- name: GetCycleByID :one
SELECT id, organization_id, name, type, start_date, end_date, status, okr_definition_deadline, mid_review_date, created_at, updated_at
FROM cycles
WHERE id = $1
  AND organization_id = $2
  AND deleted_at IS NULL
`

type GetCycleByIDParams struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
}

type GetCycleByIDRow struct {
	ID                    uuid.UUID
	OrganizationID        uuid.UUID
	Name                  string
	Type                  string
	StartDate             pgtype.Date
	EndDate               pgtype.Date
	Status                string
	OkrDefinitionDeadline pgtype.Date
	MidReviewDate         pgtype.Date
	CreatedAt             time.Time
	UpdatedAt             time.Time
}

func (q *Queries) GetCycleByID(ctx context.Context, arg GetCycleByIDParams) (GetCycleByIDRow, error) {
	row := q.db.QueryRow(ctx, getCycleByID, arg.ID, arg.OrganizationID)
	var i GetCycleByIDRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Type,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.OkrDefinitionDeadline,
		&i.MidReviewDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCycleByName = `-- name: GetCycleByName :one
SELECT id, organization_id, name, type, start_date, end_date, status, okr_definition_deadline, mid_review_date, created_at, updated_at
FROM cycles
WHERE organization_id = $1
  AND LOWER(name) = LOWER($2)
  AND deleted_at IS NULL
`

type GetCycleByNameParams struct {
	OrganizationID uuid.UUID
	Lower          string
}

type GetCycleByNameRow struct {
	ID                    uuid.UUID
	OrganizationID        uuid.UUID
	Name                  string
	Type                  string
	StartDate             pgtype.Date
	EndDate               pgtype.Date
	Status                string
	OkrDefinitionDeadline pgtype.Date
	MidReviewDate         pgtype.Date
	CreatedAt             time.Time
	UpdatedAt             time.Time
}

func (q *Queries) GetCycleByName(ctx context.Context, arg GetCycleByNameParams) (GetCycleByNameRow, error) {
	row := q.db.QueryRow(ctx, getCycleByName, arg.OrganizationID, arg.Lower)
	var i GetCycleByNameRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Type,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.OkrDefinitionDeadline,
		&i.MidReviewDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCycles = `-- name: ListCycles :many
SELECT id, organization_id, name, type, start_date, end_date, status, okr_definition_deadline, mid_review_date, created_at, updated_at
FROM cycles
WHERE organization_id = $1
  AND deleted_at IS NULL
ORDER BY start_date ASC, created_at ASC
LIMIT $2 OFFSET $3
`

type ListCyclesParams struct {
	OrganizationID uuid.UUID
	Limit          int32
	Offset         int32
}

type ListCyclesRow struct {
	ID                    uuid.UUID
	OrganizationID        uuid.UUID
	Name                  string
	Type                  string
	StartDate             pgtype.Date
	EndDate               pgtype.Date
	Status                string
	OkrDefinitionDeadline pgtype.Date
	MidReviewDate         pgtype.Date
	CreatedAt             time.Time
	UpdatedAt             time.Time
}

func (q *Queries) ListCycles(ctx context.Context, arg ListCyclesParams) ([]ListCyclesRow, error) {
	rows, err := q.db.Query(ctx, listCycles, arg.OrganizationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCyclesRow
	for rows.Next() {
		var i ListCyclesRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Type,
			&i.StartDate,
			&i.EndDate,
			&i.Status,
			&i.OkrDefinitionDeadline,
			&i.MidReviewDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCyclesByStatus = `-- name: ListCyclesByStatus :many
SELECT id, organization_id, name, type, start_date, end_date, status, okr_definition_deadline, mid_review_date, created_at, updated_at
FROM cycles
WHERE organization_id = $1
  AND status = $2
  AND deleted_at IS NULL
ORDER BY start_date ASC, created_at ASC
LIMIT $3 OFFSET $4
`

type ListCyclesByStatusParams struct {
	OrganizationID uuid.UUID
	Status         string
	Limit          int32
	Offset         int32
}

type ListCyclesByStatusRow struct {
	ID                    uuid.UUID
	OrganizationID        uuid.UUID
	Name                  string
	Type                  string
	StartDate             pgtype.Date
	EndDate               pgtype.Date
	Status                string
	OkrDefinitionDeadline pgtype.Date
	MidReviewDate         pgtype.Date
	CreatedAt             time.Time
	UpdatedAt             time.Time
}

func (q *Queries) ListCyclesByStatus(ctx context.Context, arg ListCyclesByStatusParams) ([]ListCyclesByStatusRow, error) {
	rows, err := q.db.Query(ctx, listCyclesByStatus,
		arg.OrganizationID,
		arg.Status,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCyclesByStatusRow
	for rows.Next() {
		var i ListCyclesByStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Type,
			&i.StartDate,
			&i.EndDate,
			&i.Status,
			&i.OkrDefinitionDeadline,
			&i.MidReviewDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteCycle = `-- name: SoftDeleteCycle :exec
UPDATE cycles
SET deleted_at = NOW()
WHERE id = $1
  AND organization_id = $2
  AND deleted_at IS NULL
`

type SoftDeleteCycleParams struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
}

func (q *Queries) SoftDeleteCycle(ctx context.Context, arg SoftDeleteCycleParams) error {
	_, err := q.db.Exec(ctx, softDeleteCycle, arg.ID, arg.OrganizationID)
	return err
}

const updateCycle = `-- name: UpdateCycle :one
UPDATE cycles
SET name                    = $3,
    type                    = $4,
    start_date              = $5,
    end_date                = $6,
    status                  = $7,
    okr_definition_deadline = $8,
    mid_review_date         = $9,
    updated_at              = NOW()
WHERE id = $1
  AND organization_id = $2
  AND deleted_at IS NULL
RETURNING id, organization_id, name, type, start_date, end_date, status, okr_definition_deadline, mid_review_date, created_at, updated_at
`

type UpdateCycleParams struct {
	ID                    uuid.UUID
	OrganizationID        uuid.UUID
	Name                  string
	Type                  string
	StartDate             pgtype.Date
	EndDate               pgtype.Date
	Status                string
	OkrDefinitionDeadline pgtype.Date
	MidReviewDate         pgtype.Date
}

type UpdateCycleRow struct {
	ID                    uuid.UUID
	OrganizationID        uuid.UUID
	Name                  string
	Type                  string
	StartDate             pgtype.Date
	EndDate               pgtype.Date
	Status                string
	OkrDefinitionDeadline pgtype.Date
	MidReviewDate         pgtype.Date
	CreatedAt             time.Time
	UpdatedAt             time.Time
}

func (q *Queries) UpdateCycle(ctx context.Context, arg UpdateCycleParams) (UpdateCycleRow, error) {
	row := q.db.QueryRow(ctx, updateCycle,
		arg.ID,
		arg.OrganizationID,
		arg.Name,
		arg.Type,
		arg.StartDate,
		arg.EndDate,
		arg.Status,
		arg.OkrDefinitionDeadline,
		arg.MidReviewDate,
	)
	var i UpdateCycleRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Type,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.OkrDefinitionDeadline,
		&i.MidReviewDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
