// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: indicators.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countIndicators = `-- name: CountIndicators :one
SELECT COUNT(*)
FROM indicators
WHERE organization_id = $1
  AND deleted_at IS NULL
  AND ($2::uuid IS NULL OR mission_id = $2)
  AND ($3::uuid IS NULL OR owner_id = $3)
  AND ($4::text IS NULL OR status = $4)
`

type CountIndicatorsParams struct {
	OrganizationID uuid.UUID
	MissionID      pgtype.UUID
	OwnerID        pgtype.UUID
	Status         pgtype.Text
}

func (q *Queries) CountIndicators(ctx context.Context, arg CountIndicatorsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countIndicators,
		arg.OrganizationID,
		arg.MissionID,
		arg.OwnerID,
		arg.Status,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createIndicator = `-- name: CreateIndicator :one
INSERT INTO indicators (id, organization_id, mission_id, owner_id, title, description, target_value, current_value, unit, status, due_date, measurement_mode, goal_type, low_threshold, high_threshold, period_start, period_end, team_id, linked_survey_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19)
RETURNING id, organization_id, mission_id, owner_id, title, description, target_value, current_value, unit, status, due_date, measurement_mode, goal_type, low_threshold, high_threshold, period_start, period_end, team_id, linked_survey_id, created_at, updated_at
`

type CreateIndicatorParams struct {
	ID              uuid.UUID
	OrganizationID  uuid.UUID
	MissionID       uuid.UUID
	OwnerID         uuid.UUID
	Title           string
	Description     pgtype.Text
	TargetValue     pgtype.Numeric
	CurrentValue    pgtype.Numeric
	Unit            pgtype.Text
	Status          string
	DueDate         pgtype.Date
	MeasurementMode string
	GoalType        string
	LowThreshold    pgtype.Numeric
	HighThreshold   pgtype.Numeric
	PeriodStart     pgtype.Date
	PeriodEnd       pgtype.Date
	TeamID          pgtype.UUID
	LinkedSurveyID  pgtype.UUID
}

type CreateIndicatorRow struct {
	ID              uuid.UUID
	OrganizationID  uuid.UUID
	MissionID       uuid.UUID
	OwnerID         uuid.UUID
	Title           string
	Description     pgtype.Text
	TargetValue     pgtype.Numeric
	CurrentValue    pgtype.Numeric
	Unit            pgtype.Text
	Status          string
	DueDate         pgtype.Date
	MeasurementMode string
	GoalType        string
	LowThreshold    pgtype.Numeric
	HighThreshold   pgtype.Numeric
	PeriodStart     pgtype.Date
	PeriodEnd       pgtype.Date
	TeamID          pgtype.UUID
	LinkedSurveyID  pgtype.UUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

func (q *Queries) CreateIndicator(ctx context.Context, arg CreateIndicatorParams) (CreateIndicatorRow, error) {
	row := q.db.QueryRow(ctx, createIndicator,
		arg.ID,
		arg.OrganizationID,
		arg.MissionID,
		arg.OwnerID,
		arg.Title,
		arg.Description,
		arg.TargetValue,
		arg.CurrentValue,
		arg.Unit,
		arg.Status,
		arg.DueDate,
		arg.MeasurementMode,
		arg.GoalType,
		arg.LowThreshold,
		arg.HighThreshold,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.TeamID,
		arg.LinkedSurveyID,
	)
	var i CreateIndicatorRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.MissionID,
		&i.OwnerID,
		&i.Title,
		&i.Description,
		&i.TargetValue,
		&i.CurrentValue,
		&i.Unit,
		&i.Status,
		&i.DueDate,
		&i.MeasurementMode,
		&i.GoalType,
		&i.LowThreshold,
		&i.HighThreshold,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.TeamID,
		&i.LinkedSurveyID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIndicatorByID = `-- name: GetIndicatorByID :one
SELECT id, organization_id, mission_id, owner_id, title, description, target_value, current_value, unit, status, due_date, measurement_mode, goal_type, low_threshold, high_threshold, period_start, period_end, team_id, linked_survey_id, created_at, updated_at
FROM indicators
WHERE id = $1
  AND organization_id = $2
  AND deleted_at IS NULL
`

type GetIndicatorByIDParams struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
}

type GetIndicatorByIDRow struct {
	ID              uuid.UUID
	OrganizationID  uuid.UUID
	MissionID       uuid.UUID
	OwnerID         uuid.UUID
	Title           string
	Description     pgtype.Text
	TargetValue     pgtype.Numeric
	CurrentValue    pgtype.Numeric
	Unit            pgtype.Text
	Status          string
	DueDate         pgtype.Date
	MeasurementMode string
	GoalType        string
	LowThreshold    pgtype.Numeric
	HighThreshold   pgtype.Numeric
	PeriodStart     pgtype.Date
	PeriodEnd       pgtype.Date
	TeamID          pgtype.UUID
	LinkedSurveyID  pgtype.UUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

func (q *Queries) GetIndicatorByID(ctx context.Context, arg GetIndicatorByIDParams) (GetIndicatorByIDRow, error) {
	row := q.db.QueryRow(ctx, getIndicatorByID, arg.ID, arg.OrganizationID)
	var i GetIndicatorByIDRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.MissionID,
		&i.OwnerID,
		&i.Title,
		&i.Description,
		&i.TargetValue,
		&i.CurrentValue,
		&i.Unit,
		&i.Status,
		&i.DueDate,
		&i.MeasurementMode,
		&i.GoalType,
		&i.LowThreshold,
		&i.HighThreshold,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.TeamID,
		&i.LinkedSurveyID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listIndicators = `-- name: ListIndicators :many
SELECT id, organization_id, mission_id, owner_id, title, description, target_value, current_value, unit, status, due_date, measurement_mode, goal_type, low_threshold, high_threshold, period_start, period_end, team_id, linked_survey_id, created_at, updated_at
FROM indicators
WHERE organization_id = $1
  AND deleted_at IS NULL
  AND ($4::uuid IS NULL OR mission_id = $4)
  AND ($5::uuid IS NULL OR owner_id = $5)
  AND ($6::text IS NULL OR status = $6)
ORDER BY created_at ASC
LIMIT $2 OFFSET $3
`

type ListIndicatorsParams struct {
	OrganizationID uuid.UUID
	Limit          int32
	Offset         int32
	MissionID      pgtype.UUID
	OwnerID        pgtype.UUID
	Status         pgtype.Text
}

type ListIndicatorsRow struct {
	ID              uuid.UUID
	OrganizationID  uuid.UUID
	MissionID       uuid.UUID
	OwnerID         uuid.UUID
	Title           string
	Description     pgtype.Text
	TargetValue     pgtype.Numeric
	CurrentValue    pgtype.Numeric
	Unit            pgtype.Text
	Status          string
	DueDate         pgtype.Date
	MeasurementMode string
	GoalType        string
	LowThreshold    pgtype.Numeric
	HighThreshold   pgtype.Numeric
	PeriodStart     pgtype.Date
	PeriodEnd       pgtype.Date
	TeamID          pgtype.UUID
	LinkedSurveyID  pgtype.UUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

func (q *Queries) ListIndicators(ctx context.Context, arg ListIndicatorsParams) ([]ListIndicatorsRow, error) {
	rows, err := q.db.Query(ctx, listIndicators,
		arg.OrganizationID,
		arg.Limit,
		arg.Offset,
		arg.MissionID,
		arg.OwnerID,
		arg.Status,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIndicatorsRow
	for rows.Next() {
		var i ListIndicatorsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.MissionID,
			&i.OwnerID,
			&i.Title,
			&i.Description,
			&i.TargetValue,
			&i.CurrentValue,
			&i.Unit,
			&i.Status,
			&i.DueDate,
			&i.MeasurementMode,
			&i.GoalType,
			&i.LowThreshold,
			&i.HighThreshold,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.TeamID,
			&i.LinkedSurveyID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteIndicator = `-- name: SoftDeleteIndicator :execrows
UPDATE indicators
SET deleted_at = NOW()
WHERE id = $1
  AND organization_id = $2
  AND deleted_at IS NULL
`

type SoftDeleteIndicatorParams struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
}

func (q *Queries) SoftDeleteIndicator(ctx context.Context, arg SoftDeleteIndicatorParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteIndicator, arg.ID, arg.OrganizationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateIndicator = `-- name: UpdateIndicator :one
UPDATE indicators
SET title            = $3,
    description      = $4,
    owner_id         = $5,
    target_value     = $6,
    current_value    = $7,
    unit             = $8,
    status           = $9,
    due_date         = $10,
    measurement_mode = $11,
    goal_type        = $12,
    low_threshold    = $13,
    high_threshold   = $14,
    period_start     = $15,
    period_end       = $16,
    team_id          = $17,
    linked_survey_id = $18,
    updated_at       = NOW()
WHERE id = $1
  AND organization_id = $2
  AND deleted_at IS NULL
RETURNING id, organization_id, mission_id, owner_id, title, description, target_value, current_value, unit, status, due_date, measurement_mode, goal_type, low_threshold, high_threshold, period_start, period_end, team_id, linked_survey_id, created_at, updated_at
`

type UpdateIndicatorParams struct {
	ID              uuid.UUID
	OrganizationID  uuid.UUID
	Title           string
	Description     pgtype.Text
	OwnerID         uuid.UUID
	TargetValue     pgtype.Numeric
	CurrentValue    pgtype.Numeric
	Unit            pgtype.Text
	Status          string
	DueDate         pgtype.Date
	MeasurementMode string
	GoalType        string
	LowThreshold    pgtype.Numeric
	HighThreshold   pgtype.Numeric
	PeriodStart     pgtype.Date
	PeriodEnd       pgtype.Date
	TeamID          pgtype.UUID
	LinkedSurveyID  pgtype.UUID
}

type UpdateIndicatorRow struct {
	ID              uuid.UUID
	OrganizationID  uuid.UUID
	MissionID       uuid.UUID
	OwnerID         uuid.UUID
	Title           string
	Description     pgtype.Text
	TargetValue     pgtype.Numeric
	CurrentValue    pgtype.Numeric
	Unit            pgtype.Text
	Status          string
	DueDate         pgtype.Date
	MeasurementMode string
	GoalType        string
	LowThreshold    pgtype.Numeric
	HighThreshold   pgtype.Numeric
	PeriodStart     pgtype.Date
	PeriodEnd       pgtype.Date
	TeamID          pgtype.UUID
	LinkedSurveyID  pgtype.UUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

func (q *Queries) UpdateIndicator(ctx context.Context, arg UpdateIndicatorParams) (UpdateIndicatorRow, error) {
	row := q.db.QueryRow(ctx, updateIndicator,
		arg.ID,
		arg.OrganizationID,
		arg.Title,
		arg.Description,
		arg.OwnerID,
		arg.TargetValue,
		arg.CurrentValue,
		arg.Unit,
		arg.Status,
		arg.DueDate,
		arg.MeasurementMode,
		arg.GoalType,
		arg.LowThreshold,
		arg.HighThreshold,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.TeamID,
		arg.LinkedSurveyID,
	)
	var i UpdateIndicatorRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.MissionID,
		&i.OwnerID,
		&i.Title,
		&i.Description,
		&i.TargetValue,
		&i.CurrentValue,
		&i.Unit,
		&i.Status,
		&i.DueDate,
		&i.MeasurementMode,
		&i.GoalType,
		&i.LowThreshold,
		&i.HighThreshold,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.TeamID,
		&i.LinkedSurveyID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
