// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: missions.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countMissions = `-- name: CountMissions :one
SELECT COUNT(*)
FROM missions
WHERE organization_id = $1
  AND deleted_at IS NULL
  AND ($2::uuid IS NULL OR owner_id = $2)
  AND ($3::uuid IS NULL OR team_id = $3)
  AND ($4::text IS NULL OR status = $4)
  AND (
    NOT $5::bool
    OR ($6::uuid IS NULL AND parent_id IS NULL)
    OR parent_id = $6
  )
`

type CountMissionsParams struct {
	OrganizationID uuid.UUID
	OwnerID        pgtype.UUID
	TeamID         pgtype.UUID
	Status         pgtype.Text
	FilterByParent bool
	ParentID       pgtype.UUID
}

func (q *Queries) CountMissions(ctx context.Context, arg CountMissionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countMissions,
		arg.OrganizationID,
		arg.OwnerID,
		arg.TeamID,
		arg.Status,
		arg.FilterByParent,
		arg.ParentID,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMission = `-- name: CreateMission :one
INSERT INTO missions (id, organization_id, parent_id, owner_id, team_id, title, description, status, visibility, kanban_status, start_date, end_date, completed_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, organization_id, parent_id, owner_id, team_id, title, description, status, visibility, kanban_status, start_date, end_date, completed_at, created_at, updated_at
`

type CreateMissionParams struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	ParentID       pgtype.UUID
	OwnerID        uuid.UUID
	TeamID         pgtype.UUID
	Title          string
	Description    pgtype.Text
	Status         string
	Visibility     string
	KanbanStatus   string
	StartDate      pgtype.Date
	EndDate        pgtype.Date
	CompletedAt    pgtype.Timestamptz
}

type CreateMissionRow struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	ParentID       pgtype.UUID
	OwnerID        uuid.UUID
	TeamID         pgtype.UUID
	Title          string
	Description    pgtype.Text
	Status         string
	Visibility     string
	KanbanStatus   string
	StartDate      pgtype.Date
	EndDate        pgtype.Date
	CompletedAt    pgtype.Timestamptz
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

func (q *Queries) CreateMission(ctx context.Context, arg CreateMissionParams) (CreateMissionRow, error) {
	row := q.db.QueryRow(ctx, createMission,
		arg.ID,
		arg.OrganizationID,
		arg.ParentID,
		arg.OwnerID,
		arg.TeamID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Visibility,
		arg.KanbanStatus,
		arg.StartDate,
		arg.EndDate,
		arg.CompletedAt,
	)
	var i CreateMissionRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ParentID,
		&i.OwnerID,
		&i.TeamID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Visibility,
		&i.KanbanStatus,
		&i.StartDate,
		&i.EndDate,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMissionMemberByUser = `-- name: DeleteMissionMemberByUser :exec
DELETE FROM mission_members
WHERE org_id = $1 AND mission_id = $2 AND user_id = $3
`

type DeleteMissionMemberByUserParams struct {
	OrgID     uuid.UUID
	MissionID uuid.UUID
	UserID    uuid.UUID
}

func (q *Queries) DeleteMissionMemberByUser(ctx context.Context, arg DeleteMissionMemberByUserParams) error {
	_, err := q.db.Exec(ctx, deleteMissionMemberByUser, arg.OrgID, arg.MissionID, arg.UserID)
	return err
}

const deleteMissionMembers = `-- name: DeleteMissionMembers :exec
DELETE FROM mission_members
WHERE org_id = $1 AND mission_id = $2
`

type DeleteMissionMembersParams struct {
	OrgID     uuid.UUID
	MissionID uuid.UUID
}

func (q *Queries) DeleteMissionMembers(ctx context.Context, arg DeleteMissionMembersParams) error {
	_, err := q.db.Exec(ctx, deleteMissionMembers, arg.OrgID, arg.MissionID)
	return err
}

const deleteMissionTagByTag = `-- name: DeleteMissionTagByTag :exec
DELETE FROM mission_tags
WHERE org_id = $1 AND mission_id = $2 AND tag_id = $3
`

type DeleteMissionTagByTagParams struct {
	OrgID     uuid.UUID
	MissionID uuid.UUID
	TagID     uuid.UUID
}

func (q *Queries) DeleteMissionTagByTag(ctx context.Context, arg DeleteMissionTagByTagParams) error {
	_, err := q.db.Exec(ctx, deleteMissionTagByTag, arg.OrgID, arg.MissionID, arg.TagID)
	return err
}

const deleteMissionTags = `-- name: DeleteMissionTags :exec
DELETE FROM mission_tags
WHERE org_id = $1 AND mission_id = $2
`

type DeleteMissionTagsParams struct {
	OrgID     uuid.UUID
	MissionID uuid.UUID
}

func (q *Queries) DeleteMissionTags(ctx context.Context, arg DeleteMissionTagsParams) error {
	_, err := q.db.Exec(ctx, deleteMissionTags, arg.OrgID, arg.MissionID)
	return err
}

const getMissionByID = `-- name: GetMissionByID :one
SELECT id, organization_id, parent_id, owner_id, team_id, title, description, status, visibility, kanban_status, start_date, end_date, completed_at, created_at, updated_at
FROM missions
WHERE id = $1
  AND organization_id = $2
  AND deleted_at IS NULL
`

type GetMissionByIDParams struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
}

type GetMissionByIDRow struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	ParentID       pgtype.UUID
	OwnerID        uuid.UUID
	TeamID         pgtype.UUID
	Title          string
	Description    pgtype.Text
	Status         string
	Visibility     string
	KanbanStatus   string
	StartDate      pgtype.Date
	EndDate        pgtype.Date
	CompletedAt    pgtype.Timestamptz
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

func (q *Queries) GetMissionByID(ctx context.Context, arg GetMissionByIDParams) (GetMissionByIDRow, error) {
	row := q.db.QueryRow(ctx, getMissionByID, arg.ID, arg.OrganizationID)
	var i GetMissionByIDRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ParentID,
		&i.OwnerID,
		&i.TeamID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Visibility,
		&i.KanbanStatus,
		&i.StartDate,
		&i.EndDate,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertMissionMember = `-- name: InsertMissionMember :exec
INSERT INTO mission_members (org_id, mission_id, user_id, role, joined_at)
VALUES ($1, $2, $3, $4, $5)
`

type InsertMissionMemberParams struct {
	OrgID     uuid.UUID
	MissionID uuid.UUID
	UserID    uuid.UUID
	Role      string
	JoinedAt  time.Time
}

func (q *Queries) InsertMissionMember(ctx context.Context, arg InsertMissionMemberParams) error {
	_, err := q.db.Exec(ctx, insertMissionMember,
		arg.OrgID,
		arg.MissionID,
		arg.UserID,
		arg.Role,
		arg.JoinedAt,
	)
	return err
}

const insertMissionTag = `-- name: InsertMissionTag :exec
INSERT INTO mission_tags (org_id, mission_id, tag_id)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type InsertMissionTagParams struct {
	OrgID     uuid.UUID
	MissionID uuid.UUID
	TagID     uuid.UUID
}

func (q *Queries) InsertMissionTag(ctx context.Context, arg InsertMissionTagParams) error {
	_, err := q.db.Exec(ctx, insertMissionTag, arg.OrgID, arg.MissionID, arg.TagID)
	return err
}

const listMissionMembers = `-- name: ListMissionMembers :many
SELECT org_id, mission_id, user_id, role, joined_at
FROM mission_members
WHERE org_id = $1 AND mission_id = $2
ORDER BY joined_at ASC
`

type ListMissionMembersParams struct {
	OrgID     uuid.UUID
	MissionID uuid.UUID
}

func (q *Queries) ListMissionMembers(ctx context.Context, arg ListMissionMembersParams) ([]MissionMember, error) {
	rows, err := q.db.Query(ctx, listMissionMembers, arg.OrgID, arg.MissionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MissionMember
	for rows.Next() {
		var i MissionMember
		if err := rows.Scan(
			&i.OrgID,
			&i.MissionID,
			&i.UserID,
			&i.Role,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMissionTagIDs = `-- name: ListMissionTagIDs :many

SELECT tag_id
FROM mission_tags
WHERE org_id = $1 AND mission_id = $2
ORDER BY created_at ASC
`

type ListMissionTagIDsParams struct {
	OrgID     uuid.UUID
	MissionID uuid.UUID
}

// IsMissionDescendant and SoftDeleteMissionSubtree use recursive CTEs and are
// implemented as raw pgx queries in the repository (sqlc parser does not
// handle recursive CTE column aliasing reliably).
func (q *Queries) ListMissionTagIDs(ctx context.Context, arg ListMissionTagIDsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listMissionTagIDs, arg.OrgID, arg.MissionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var tag_id uuid.UUID
		if err := rows.Scan(&tag_id); err != nil {
			return nil, err
		}
		items = append(items, tag_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMissions = `-- name: ListMissions :many
SELECT id, organization_id, parent_id, owner_id, team_id, title, description, status, visibility, kanban_status, start_date, end_date, completed_at, created_at, updated_at
FROM missions
WHERE organization_id = $1
  AND deleted_at IS NULL
  AND ($4::uuid IS NULL OR owner_id = $4)
  AND ($5::uuid IS NULL OR team_id = $5)
  AND ($6::text IS NULL OR status = $6)
  AND (
    NOT $7::bool
    OR ($8::uuid IS NULL AND parent_id IS NULL)
    OR parent_id = $8
  )
ORDER BY created_at ASC
LIMIT $2 OFFSET $3
`

type ListMissionsParams struct {
	OrganizationID uuid.UUID
	Limit          int32
	Offset         int32
	OwnerID        pgtype.UUID
	TeamID         pgtype.UUID
	Status         pgtype.Text
	FilterByParent bool
	ParentID       pgtype.UUID
}

type ListMissionsRow struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	ParentID       pgtype.UUID
	OwnerID        uuid.UUID
	TeamID         pgtype.UUID
	Title          string
	Description    pgtype.Text
	Status         string
	Visibility     string
	KanbanStatus   string
	StartDate      pgtype.Date
	EndDate        pgtype.Date
	CompletedAt    pgtype.Timestamptz
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

func (q *Queries) ListMissions(ctx context.Context, arg ListMissionsParams) ([]ListMissionsRow, error) {
	rows, err := q.db.Query(ctx, listMissions,
		arg.OrganizationID,
		arg.Limit,
		arg.Offset,
		arg.OwnerID,
		arg.TeamID,
		arg.Status,
		arg.FilterByParent,
		arg.ParentID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMissionsRow
	for rows.Next() {
		var i ListMissionsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ParentID,
			&i.OwnerID,
			&i.TeamID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Visibility,
			&i.KanbanStatus,
			&i.StartDate,
			&i.EndDate,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMission = `-- name: UpdateMission :one
UPDATE missions
SET title         = $3,
    description   = $4,
    parent_id     = $5,
    owner_id      = $6,
    team_id       = $7,
    status        = $8,
    visibility    = $9,
    kanban_status = $10,
    start_date    = $11,
    end_date      = $12,
    completed_at  = $13,
    updated_at    = NOW()
WHERE id = $1
  AND organization_id = $2
  AND deleted_at IS NULL
RETURNING id, organization_id, parent_id, owner_id, team_id, title, description, status, visibility, kanban_status, start_date, end_date, completed_at, created_at, updated_at
`

type UpdateMissionParams struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	Title          string
	Description    pgtype.Text
	ParentID       pgtype.UUID
	OwnerID        uuid.UUID
	TeamID         pgtype.UUID
	Status         string
	Visibility     string
	KanbanStatus   string
	StartDate      pgtype.Date
	EndDate        pgtype.Date
	CompletedAt    pgtype.Timestamptz
}

type UpdateMissionRow struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	ParentID       pgtype.UUID
	OwnerID        uuid.UUID
	TeamID         pgtype.UUID
	Title          string
	Description    pgtype.Text
	Status         string
	Visibility     string
	KanbanStatus   string
	StartDate      pgtype.Date
	EndDate        pgtype.Date
	CompletedAt    pgtype.Timestamptz
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

func (q *Queries) UpdateMission(ctx context.Context, arg UpdateMissionParams) (UpdateMissionRow, error) {
	row := q.db.QueryRow(ctx, updateMission,
		arg.ID,
		arg.OrganizationID,
		arg.Title,
		arg.Description,
		arg.ParentID,
		arg.OwnerID,
		arg.TeamID,
		arg.Status,
		arg.Visibility,
		arg.KanbanStatus,
		arg.StartDate,
		arg.EndDate,
		arg.CompletedAt,
	)
	var i UpdateMissionRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ParentID,
		&i.OwnerID,
		&i.TeamID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Visibility,
		&i.KanbanStatus,
		&i.StartDate,
		&i.EndDate,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
