// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: missions.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countMissions = `-- name: CountMissions :one
SELECT COUNT(*)
FROM missions
WHERE organization_id = $1
  AND deleted_at IS NULL
  AND ($2::uuid IS NULL OR cycle_id = $2)
  AND ($3::uuid IS NULL OR owner_id = $3)
  AND ($4::uuid IS NULL OR team_id = $4)
  AND ($5::text IS NULL OR status = $5)
  AND (
    NOT $6::bool
    OR ($7::uuid IS NULL AND parent_id IS NULL)
    OR parent_id = $7
  )
`

type CountMissionsParams struct {
	OrganizationID uuid.UUID
	CycleID        pgtype.UUID
	OwnerID        pgtype.UUID
	TeamID         pgtype.UUID
	Status         pgtype.Text
	FilterByParent bool
	ParentID       pgtype.UUID
}

func (q *Queries) CountMissions(ctx context.Context, arg CountMissionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countMissions,
		arg.OrganizationID,
		arg.CycleID,
		arg.OwnerID,
		arg.TeamID,
		arg.Status,
		arg.FilterByParent,
		arg.ParentID,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMission = `-- name: CreateMission :one
INSERT INTO missions (id, organization_id, cycle_id, parent_id, owner_id, team_id, title, description, status, visibility, kanban_status, sort_order, due_date, completed_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING id, organization_id, cycle_id, parent_id, owner_id, team_id, title, description, status, visibility, kanban_status, sort_order, due_date, completed_at, created_at, updated_at
`

type CreateMissionParams struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	CycleID        pgtype.UUID
	ParentID       pgtype.UUID
	OwnerID        uuid.UUID
	TeamID         pgtype.UUID
	Title          string
	Description    pgtype.Text
	Status         string
	Visibility     string
	KanbanStatus   string
	SortOrder      int32
	DueDate        pgtype.Date
	CompletedAt    pgtype.Timestamptz
}

type CreateMissionRow struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	CycleID        pgtype.UUID
	ParentID       pgtype.UUID
	OwnerID        uuid.UUID
	TeamID         pgtype.UUID
	Title          string
	Description    pgtype.Text
	Status         string
	Visibility     string
	KanbanStatus   string
	SortOrder      int32
	DueDate        pgtype.Date
	CompletedAt    pgtype.Timestamptz
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

func (q *Queries) CreateMission(ctx context.Context, arg CreateMissionParams) (CreateMissionRow, error) {
	row := q.db.QueryRow(ctx, createMission,
		arg.ID,
		arg.OrganizationID,
		arg.CycleID,
		arg.ParentID,
		arg.OwnerID,
		arg.TeamID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Visibility,
		arg.KanbanStatus,
		arg.SortOrder,
		arg.DueDate,
		arg.CompletedAt,
	)
	var i CreateMissionRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CycleID,
		&i.ParentID,
		&i.OwnerID,
		&i.TeamID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Visibility,
		&i.KanbanStatus,
		&i.SortOrder,
		&i.DueDate,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMissionByID = `-- name: GetMissionByID :one
SELECT id, organization_id, cycle_id, parent_id, owner_id, team_id, title, description, status, visibility, kanban_status, sort_order, due_date, completed_at, created_at, updated_at
FROM missions
WHERE id = $1
  AND organization_id = $2
  AND deleted_at IS NULL
`

type GetMissionByIDParams struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
}

type GetMissionByIDRow struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	CycleID        pgtype.UUID
	ParentID       pgtype.UUID
	OwnerID        uuid.UUID
	TeamID         pgtype.UUID
	Title          string
	Description    pgtype.Text
	Status         string
	Visibility     string
	KanbanStatus   string
	SortOrder      int32
	DueDate        pgtype.Date
	CompletedAt    pgtype.Timestamptz
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

func (q *Queries) GetMissionByID(ctx context.Context, arg GetMissionByIDParams) (GetMissionByIDRow, error) {
	row := q.db.QueryRow(ctx, getMissionByID, arg.ID, arg.OrganizationID)
	var i GetMissionByIDRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CycleID,
		&i.ParentID,
		&i.OwnerID,
		&i.TeamID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Visibility,
		&i.KanbanStatus,
		&i.SortOrder,
		&i.DueDate,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMissions = `-- name: ListMissions :many
SELECT id, organization_id, cycle_id, parent_id, owner_id, team_id, title, description, status, visibility, kanban_status, sort_order, due_date, completed_at, created_at, updated_at
FROM missions
WHERE organization_id = $1
  AND deleted_at IS NULL
  AND ($4::uuid IS NULL OR cycle_id = $4)
  AND ($5::uuid IS NULL OR owner_id = $5)
  AND ($6::uuid IS NULL OR team_id = $6)
  AND ($7::text IS NULL OR status = $7)
  AND (
    NOT $8::bool
    OR ($9::uuid IS NULL AND parent_id IS NULL)
    OR parent_id = $9
  )
ORDER BY sort_order ASC, created_at ASC
LIMIT $2 OFFSET $3
`

type ListMissionsParams struct {
	OrganizationID uuid.UUID
	Limit          int32
	Offset         int32
	CycleID        pgtype.UUID
	OwnerID        pgtype.UUID
	TeamID         pgtype.UUID
	Status         pgtype.Text
	FilterByParent bool
	ParentID       pgtype.UUID
}

type ListMissionsRow struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	CycleID        pgtype.UUID
	ParentID       pgtype.UUID
	OwnerID        uuid.UUID
	TeamID         pgtype.UUID
	Title          string
	Description    pgtype.Text
	Status         string
	Visibility     string
	KanbanStatus   string
	SortOrder      int32
	DueDate        pgtype.Date
	CompletedAt    pgtype.Timestamptz
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

func (q *Queries) ListMissions(ctx context.Context, arg ListMissionsParams) ([]ListMissionsRow, error) {
	rows, err := q.db.Query(ctx, listMissions,
		arg.OrganizationID,
		arg.Limit,
		arg.Offset,
		arg.CycleID,
		arg.OwnerID,
		arg.TeamID,
		arg.Status,
		arg.FilterByParent,
		arg.ParentID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMissionsRow
	for rows.Next() {
		var i ListMissionsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.CycleID,
			&i.ParentID,
			&i.OwnerID,
			&i.TeamID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Visibility,
			&i.KanbanStatus,
			&i.SortOrder,
			&i.DueDate,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMission = `-- name: UpdateMission :one
UPDATE missions
SET title         = $3,
    description   = $4,
    cycle_id      = $5,
    parent_id     = $6,
    owner_id      = $7,
    team_id       = $8,
    status        = $9,
    visibility    = $10,
    kanban_status = $11,
    sort_order    = $12,
    due_date      = $13,
    completed_at  = $14,
    updated_at    = NOW()
WHERE id = $1
  AND organization_id = $2
  AND deleted_at IS NULL
RETURNING id, organization_id, cycle_id, parent_id, owner_id, team_id, title, description, status, visibility, kanban_status, sort_order, due_date, completed_at, created_at, updated_at
`

type UpdateMissionParams struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	Title          string
	Description    pgtype.Text
	CycleID        pgtype.UUID
	ParentID       pgtype.UUID
	OwnerID        uuid.UUID
	TeamID         pgtype.UUID
	Status         string
	Visibility     string
	KanbanStatus   string
	SortOrder      int32
	DueDate        pgtype.Date
	CompletedAt    pgtype.Timestamptz
}

type UpdateMissionRow struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	CycleID        pgtype.UUID
	ParentID       pgtype.UUID
	OwnerID        uuid.UUID
	TeamID         pgtype.UUID
	Title          string
	Description    pgtype.Text
	Status         string
	Visibility     string
	KanbanStatus   string
	SortOrder      int32
	DueDate        pgtype.Date
	CompletedAt    pgtype.Timestamptz
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

func (q *Queries) UpdateMission(ctx context.Context, arg UpdateMissionParams) (UpdateMissionRow, error) {
	row := q.db.QueryRow(ctx, updateMission,
		arg.ID,
		arg.OrganizationID,
		arg.Title,
		arg.Description,
		arg.CycleID,
		arg.ParentID,
		arg.OwnerID,
		arg.TeamID,
		arg.Status,
		arg.Visibility,
		arg.KanbanStatus,
		arg.SortOrder,
		arg.DueDate,
		arg.CompletedAt,
	)
	var i UpdateMissionRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CycleID,
		&i.ParentID,
		&i.OwnerID,
		&i.TeamID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Visibility,
		&i.KanbanStatus,
		&i.SortOrder,
		&i.DueDate,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
