// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Cycle struct {
	ID                    uuid.UUID
	OrganizationID        uuid.UUID
	Name                  string
	Type                  string
	StartDate             pgtype.Date
	EndDate               pgtype.Date
	Status                string
	OkrDefinitionDeadline pgtype.Date
	MidReviewDate         pgtype.Date
	CreatedAt             time.Time
	UpdatedAt             time.Time
	DeletedAt             pgtype.Timestamptz
}

type Organization struct {
	ID        uuid.UUID
	Name      string
	Domain    string
	Workspace string
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt pgtype.Timestamptz
}

type OrganizationMembership struct {
	ID              uuid.UUID
	OrganizationID  uuid.UUID
	UserID          uuid.UUID
	Role            string
	Status          string
	InvitedByUserID pgtype.UUID
	JoinedAt        pgtype.Timestamptz
	CreatedAt       time.Time
	UpdatedAt       time.Time
	DeletedAt       pgtype.Timestamptz
}

type RefreshToken struct {
	ID                   uuid.UUID
	UserID               uuid.UUID
	TokenHash            string
	ExpiresAt            time.Time
	RevokedAt            pgtype.Timestamptz
	CreatedAt            time.Time
	ActiveOrganizationID pgtype.UUID
}

type Role struct {
	ID          uuid.UUID
	Slug        string
	Name        string
	Description pgtype.Text
	Type        string
	Scope       string
	IsDefault   bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Team struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	Name           string
	Description    pgtype.Text
	Color          string
	Status         string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	DeletedAt      pgtype.Timestamptz
}

type TeamMember struct {
	ID         uuid.UUID
	TeamID     uuid.UUID
	UserID     uuid.UUID
	RoleInTeam string
	JoinedAt   time.Time
	CreatedAt  time.Time
	UpdatedAt  time.Time
	DeletedAt  pgtype.Timestamptz
}

type User struct {
	ID            uuid.UUID
	Email         string
	PasswordHash  string
	Status        string
	IsSystemAdmin bool
	CreatedAt     time.Time
	UpdatedAt     time.Time
	DeletedAt     pgtype.Timestamptz
	FirstName     string
	LastName      string
	Nickname      pgtype.Text
	JobTitle      pgtype.Text
	BirthDate     pgtype.Date
	Language      string
	Gender        pgtype.Text
	Phone         pgtype.Text
}
