// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Checkin struct {
	ID            uuid.UUID
	OrgID         uuid.UUID
	IndicatorID   uuid.UUID
	AuthorID      uuid.UUID
	Value         string
	PreviousValue pgtype.Text
	Confidence    string
	Note          pgtype.Text
	Mentions      []string
	CreatedAt     time.Time
	UpdatedAt     time.Time
	DeletedAt     pgtype.Timestamptz
}

type Cycle struct {
	ID                    uuid.UUID
	OrganizationID        uuid.UUID
	Name                  string
	Type                  string
	StartDate             pgtype.Date
	EndDate               pgtype.Date
	Status                string
	OkrDefinitionDeadline pgtype.Date
	MidReviewDate         pgtype.Date
	CreatedAt             time.Time
	UpdatedAt             time.Time
	DeletedAt             pgtype.Timestamptz
}

type Indicator struct {
	ID              uuid.UUID
	OrganizationID  uuid.UUID
	MissionID       uuid.UUID
	OwnerID         uuid.UUID
	Title           string
	Description     pgtype.Text
	TargetValue     pgtype.Numeric
	CurrentValue    pgtype.Numeric
	Unit            pgtype.Text
	Status          string
	DueDate         pgtype.Date
	CreatedAt       time.Time
	UpdatedAt       time.Time
	DeletedAt       pgtype.Timestamptz
	MeasurementMode string
	GoalType        string
	LowThreshold    pgtype.Numeric
	HighThreshold   pgtype.Numeric
	PeriodStart     pgtype.Date
	PeriodEnd       pgtype.Date
	TeamID          pgtype.UUID
	LinkedSurveyID  pgtype.UUID
}

type Mission struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	ParentID       pgtype.UUID
	OwnerID        uuid.UUID
	TeamID         pgtype.UUID
	Title          string
	Description    pgtype.Text
	Status         string
	Visibility     string
	KanbanStatus   string
	StartDate      pgtype.Date
	EndDate        pgtype.Date
	CompletedAt    pgtype.Timestamptz
	CreatedAt      time.Time
	UpdatedAt      time.Time
	DeletedAt      pgtype.Timestamptz
}

type MissionMember struct {
	OrgID     uuid.UUID
	MissionID uuid.UUID
	UserID    uuid.UUID
	Role      string
	JoinedAt  time.Time
}

type MissionTag struct {
	OrgID     uuid.UUID
	MissionID uuid.UUID
	TagID     uuid.UUID
	CreatedAt time.Time
}

type Organization struct {
	ID        uuid.UUID
	Name      string
	Domain    string
	Workspace string
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt pgtype.Timestamptz
}

type OrganizationMembership struct {
	ID              uuid.UUID
	OrganizationID  uuid.UUID
	UserID          uuid.UUID
	Role            string
	Status          string
	InvitedByUserID pgtype.UUID
	JoinedAt        pgtype.Timestamptz
	CreatedAt       time.Time
	UpdatedAt       time.Time
	DeletedAt       pgtype.Timestamptz
}

type RefreshToken struct {
	ID                   uuid.UUID
	UserID               uuid.UUID
	TokenHash            string
	ExpiresAt            time.Time
	RevokedAt            pgtype.Timestamptz
	CreatedAt            time.Time
	ActiveOrganizationID pgtype.UUID
}

type Role struct {
	ID          uuid.UUID
	Slug        string
	Name        string
	Description pgtype.Text
	Type        string
	Scope       string
	IsDefault   bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Tag struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	Name           string
	Color          string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	DeletedAt      pgtype.Timestamptz
}

type Task struct {
	ID                      uuid.UUID
	OrganizationID          uuid.UUID
	MissionID               uuid.UUID
	IndicatorID             pgtype.UUID
	AssigneeID              uuid.UUID
	Title                   string
	Description             pgtype.Text
	Status                  string
	DueDate                 pgtype.Date
	CompletedAt             pgtype.Timestamptz
	CreatedAt               time.Time
	UpdatedAt               time.Time
	DeletedAt               pgtype.Timestamptz
	ParentTaskID            pgtype.UUID
	TeamID                  pgtype.UUID
	ContributesToMissionIds []uuid.UUID
}

type Team struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	Name           string
	Description    pgtype.Text
	Color          string
	Status         string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	DeletedAt      pgtype.Timestamptz
}

type TeamMember struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	TeamID         uuid.UUID
	UserID         uuid.UUID
	RoleInTeam     string
	JoinedAt       time.Time
	CreatedAt      time.Time
	UpdatedAt      time.Time
	DeletedAt      pgtype.Timestamptz
}

type User struct {
	ID            uuid.UUID
	Email         string
	PasswordHash  string
	Status        string
	IsSystemAdmin bool
	CreatedAt     time.Time
	UpdatedAt     time.Time
	DeletedAt     pgtype.Timestamptz
	FirstName     string
	LastName      string
	Nickname      pgtype.Text
	JobTitle      pgtype.Text
	BirthDate     pgtype.Date
	Language      string
	Gender        pgtype.Text
	Phone         pgtype.Text
}
