// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0

package sqlc

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Organization struct {
	ID        uuid.UUID
	Name      string
	Domain    string
	Workspace string
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt pgtype.Timestamptz
}

type OrganizationMembership struct {
	ID              uuid.UUID
	OrganizationID  uuid.UUID
	UserID          uuid.UUID
	Role            string
	Status          string
	InvitedByUserID pgtype.UUID
	JoinedAt        pgtype.Timestamptz
	CreatedAt       time.Time
	UpdatedAt       time.Time
	DeletedAt       pgtype.Timestamptz
}

type RefreshToken struct {
	ID                   uuid.UUID
	UserID               uuid.UUID
	TokenHash            string
	ExpiresAt            time.Time
	RevokedAt            pgtype.Timestamptz
	CreatedAt            time.Time
	ActiveOrganizationID pgtype.UUID
}

type User struct {
	ID            uuid.UUID
	Name          string
	Email         string
	PasswordHash  string
	Status        string
	IsSystemAdmin bool
	CreatedAt     time.Time
	UpdatedAt     time.Time
	DeletedAt     pgtype.Timestamptz
}
