// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: organizations.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countOrganizations = `-- name: CountOrganizations :one
SELECT COUNT(*) FROM organizations
WHERE deleted_at IS NULL
`

func (q *Queries) CountOrganizations(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countOrganizations)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOrganizationsByStatus = `-- name: CountOrganizationsByStatus :one
SELECT COUNT(*) FROM organizations
WHERE status = $1
  AND deleted_at IS NULL
`

func (q *Queries) CountOrganizationsByStatus(ctx context.Context, status string) (int64, error) {
	row := q.db.QueryRow(ctx, countOrganizationsByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organizations (name, domain, workspace, status)
VALUES ($1, $2, $3, $4)
RETURNING id, name, domain, workspace, status, created_at, updated_at
`

type CreateOrganizationParams struct {
	Name      string
	Domain    string
	Workspace string
	Status    string
}

type CreateOrganizationRow struct {
	ID        uuid.UUID
	Name      string
	Domain    string
	Workspace string
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (CreateOrganizationRow, error) {
	row := q.db.QueryRow(ctx, createOrganization,
		arg.Name,
		arg.Domain,
		arg.Workspace,
		arg.Status,
	)
	var i CreateOrganizationRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Domain,
		&i.Workspace,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationByDomain = `-- name: GetOrganizationByDomain :one
SELECT id, name, domain, workspace, status, created_at, updated_at FROM organizations
WHERE LOWER(domain) = LOWER($1)
  AND deleted_at IS NULL
`

type GetOrganizationByDomainRow struct {
	ID        uuid.UUID
	Name      string
	Domain    string
	Workspace string
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) GetOrganizationByDomain(ctx context.Context, lower string) (GetOrganizationByDomainRow, error) {
	row := q.db.QueryRow(ctx, getOrganizationByDomain, lower)
	var i GetOrganizationByDomainRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Domain,
		&i.Workspace,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationByID = `-- name: GetOrganizationByID :one
SELECT id, name, domain, workspace, status, created_at, updated_at FROM organizations
WHERE id = $1
  AND deleted_at IS NULL
`

type GetOrganizationByIDRow struct {
	ID        uuid.UUID
	Name      string
	Domain    string
	Workspace string
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) GetOrganizationByID(ctx context.Context, id uuid.UUID) (GetOrganizationByIDRow, error) {
	row := q.db.QueryRow(ctx, getOrganizationByID, id)
	var i GetOrganizationByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Domain,
		&i.Workspace,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationByWorkspace = `-- name: GetOrganizationByWorkspace :one
SELECT id, name, domain, workspace, status, created_at, updated_at FROM organizations
WHERE workspace = $1
  AND deleted_at IS NULL
`

type GetOrganizationByWorkspaceRow struct {
	ID        uuid.UUID
	Name      string
	Domain    string
	Workspace string
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) GetOrganizationByWorkspace(ctx context.Context, workspace string) (GetOrganizationByWorkspaceRow, error) {
	row := q.db.QueryRow(ctx, getOrganizationByWorkspace, workspace)
	var i GetOrganizationByWorkspaceRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Domain,
		&i.Workspace,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOrganizations = `-- name: ListOrganizations :many
SELECT id, name, domain, workspace, status, created_at, updated_at FROM organizations
WHERE deleted_at IS NULL
ORDER BY name ASC
LIMIT $1
OFFSET $2
`

type ListOrganizationsParams struct {
	Limit  int32
	Offset int32
}

type ListOrganizationsRow struct {
	ID        uuid.UUID
	Name      string
	Domain    string
	Workspace string
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) ListOrganizations(ctx context.Context, arg ListOrganizationsParams) ([]ListOrganizationsRow, error) {
	rows, err := q.db.Query(ctx, listOrganizations, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrganizationsRow
	for rows.Next() {
		var i ListOrganizationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Domain,
			&i.Workspace,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizationsByStatus = `-- name: ListOrganizationsByStatus :many
SELECT id, name, domain, workspace, status, created_at, updated_at FROM organizations
WHERE status = $1
  AND deleted_at IS NULL
ORDER BY name ASC
LIMIT $2
OFFSET $3
`

type ListOrganizationsByStatusParams struct {
	Status string
	Limit  int32
	Offset int32
}

type ListOrganizationsByStatusRow struct {
	ID        uuid.UUID
	Name      string
	Domain    string
	Workspace string
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) ListOrganizationsByStatus(ctx context.Context, arg ListOrganizationsByStatusParams) ([]ListOrganizationsByStatusRow, error) {
	rows, err := q.db.Query(ctx, listOrganizationsByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrganizationsByStatusRow
	for rows.Next() {
		var i ListOrganizationsByStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Domain,
			&i.Workspace,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteOrganization = `-- name: SoftDeleteOrganization :exec
UPDATE organizations
SET deleted_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteOrganization(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteOrganization, id)
	return err
}

const updateOrganization = `-- name: UpdateOrganization :one
UPDATE organizations
SET
    name       = $2,
    domain     = $3,
    workspace  = $4,
    status     = $5,
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
RETURNING id, name, domain, workspace, status, created_at, updated_at
`

type UpdateOrganizationParams struct {
	ID        uuid.UUID
	Name      string
	Domain    string
	Workspace string
	Status    string
}

type UpdateOrganizationRow struct {
	ID        uuid.UUID
	Name      string
	Domain    string
	Workspace string
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) (UpdateOrganizationRow, error) {
	row := q.db.QueryRow(ctx, updateOrganization,
		arg.ID,
		arg.Name,
		arg.Domain,
		arg.Workspace,
		arg.Status,
	)
	var i UpdateOrganizationRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Domain,
		&i.Workspace,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
