// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	ActivateInvitedMemberships(ctx context.Context, userID uuid.UUID) error
	CountOrganizationMemberships(ctx context.Context, organizationID uuid.UUID) (int64, error)
	CountOrganizationUsers(ctx context.Context, organizationID uuid.UUID) (int64, error)
	CountOrganizationUsersByStatus(ctx context.Context, arg CountOrganizationUsersByStatusParams) (int64, error)
	CountOrganizations(ctx context.Context) (int64, error)
	CountOrganizationsByStatus(ctx context.Context, status string) (int64, error)
	CountOrganizationsByUser(ctx context.Context, userID uuid.UUID) (int64, error)
	CountOrganizationsByUserAndStatus(ctx context.Context, arg CountOrganizationsByUserAndStatusParams) (int64, error)
	CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (CreateOrganizationRow, error)
	CreateOrganizationMembership(ctx context.Context, arg CreateOrganizationMembershipParams) (CreateOrganizationMembershipRow, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (CreateRefreshTokenRow, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	GetActiveOrganizationMembership(ctx context.Context, arg GetActiveOrganizationMembershipParams) (GetActiveOrganizationMembershipRow, error)
	GetOrganizationByDomain(ctx context.Context, lower string) (GetOrganizationByDomainRow, error)
	GetOrganizationByID(ctx context.Context, id uuid.UUID) (GetOrganizationByIDRow, error)
	GetOrganizationByIDForUser(ctx context.Context, arg GetOrganizationByIDForUserParams) (GetOrganizationByIDForUserRow, error)
	GetOrganizationByWorkspace(ctx context.Context, workspace string) (GetOrganizationByWorkspaceRow, error)
	GetRefreshTokenByTokenHash(ctx context.Context, tokenHash string) (GetRefreshTokenByTokenHashRow, error)
	GetUserByEmail(ctx context.Context, lower string) (GetUserByEmailRow, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error)
	ListOrganizationMemberships(ctx context.Context, arg ListOrganizationMembershipsParams) ([]ListOrganizationMembershipsRow, error)
	ListOrganizationUsers(ctx context.Context, arg ListOrganizationUsersParams) ([]ListOrganizationUsersRow, error)
	ListOrganizationUsersByStatus(ctx context.Context, arg ListOrganizationUsersByStatusParams) ([]ListOrganizationUsersByStatusRow, error)
	ListOrganizations(ctx context.Context, arg ListOrganizationsParams) ([]ListOrganizationsRow, error)
	ListOrganizationsByStatus(ctx context.Context, arg ListOrganizationsByStatusParams) ([]ListOrganizationsByStatusRow, error)
	ListOrganizationsByUser(ctx context.Context, arg ListOrganizationsByUserParams) ([]ListOrganizationsByUserRow, error)
	ListOrganizationsByUserAndStatus(ctx context.Context, arg ListOrganizationsByUserAndStatusParams) ([]ListOrganizationsByUserAndStatusRow, error)
	ListUserMemberships(ctx context.Context, arg ListUserMembershipsParams) ([]ListUserMembershipsRow, error)
	ListUserMembershipsForOrganization(ctx context.Context, arg ListUserMembershipsForOrganizationParams) ([]ListUserMembershipsForOrganizationRow, error)
	RevokeAllRefreshTokensByUserID(ctx context.Context, userID uuid.UUID) error
	RevokeRefreshToken(ctx context.Context, id uuid.UUID) error
	SoftDeleteOrganization(ctx context.Context, id uuid.UUID) error
	SoftDeleteOrganizationMembership(ctx context.Context, arg SoftDeleteOrganizationMembershipParams) error
	SoftDeleteOrganizationMembershipsByOrganization(ctx context.Context, organizationID uuid.UUID) error
	UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) (UpdateOrganizationRow, error)
	UpdateOrganizationMembership(ctx context.Context, arg UpdateOrganizationMembershipParams) (UpdateOrganizationMembershipRow, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error)
}

var _ Querier = (*Queries)(nil)
