// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: refresh_tokens.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (id, user_id, active_organization_id, token_hash, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, active_organization_id, token_hash, expires_at, revoked_at, created_at
`

type CreateRefreshTokenParams struct {
	ID                   uuid.UUID
	UserID               uuid.UUID
	ActiveOrganizationID pgtype.UUID
	TokenHash            string
	ExpiresAt            time.Time
}

type CreateRefreshTokenRow struct {
	ID                   uuid.UUID
	UserID               uuid.UUID
	ActiveOrganizationID pgtype.UUID
	TokenHash            string
	ExpiresAt            time.Time
	RevokedAt            pgtype.Timestamptz
	CreatedAt            time.Time
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (CreateRefreshTokenRow, error) {
	row := q.db.QueryRow(ctx, createRefreshToken,
		arg.ID,
		arg.UserID,
		arg.ActiveOrganizationID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i CreateRefreshTokenRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ActiveOrganizationID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getRefreshTokenByTokenHash = `-- name: GetRefreshTokenByTokenHash :one
SELECT id, user_id, active_organization_id, token_hash, expires_at, revoked_at, created_at
FROM refresh_tokens
WHERE token_hash = $1
`

type GetRefreshTokenByTokenHashRow struct {
	ID                   uuid.UUID
	UserID               uuid.UUID
	ActiveOrganizationID pgtype.UUID
	TokenHash            string
	ExpiresAt            time.Time
	RevokedAt            pgtype.Timestamptz
	CreatedAt            time.Time
}

func (q *Queries) GetRefreshTokenByTokenHash(ctx context.Context, tokenHash string) (GetRefreshTokenByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByTokenHash, tokenHash)
	var i GetRefreshTokenByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ActiveOrganizationID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const revokeAllRefreshTokensByUserID = `-- name: RevokeAllRefreshTokensByUserID :exec
UPDATE refresh_tokens
SET revoked_at = NOW()
WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAllRefreshTokensByUserID(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllRefreshTokensByUserID, userID)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens
SET revoked_at = NOW()
WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, id)
	return err
}
