// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: roles.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const listRoles = `-- name: ListRoles :many
SELECT
  r.id,
  r.slug,
  r.name,
  r.description,
  r.type,
  r.scope,
  r.is_default,
  COALESCE(COUNT(u.id), 0)::int AS users_count,
  r.created_at,
  r.updated_at
FROM roles r
LEFT JOIN organization_memberships om
  ON om.role = r.slug
  AND om.organization_id = $1
  AND om.deleted_at IS NULL
LEFT JOIN users u
  ON u.id = om.user_id
  AND u.deleted_at IS NULL
GROUP BY r.id
ORDER BY
  CASE r.type WHEN 'system' THEN 0 ELSE 1 END,
  r.created_at ASC
`

type ListRolesRow struct {
	ID          uuid.UUID
	Slug        string
	Name        string
	Description pgtype.Text
	Type        string
	Scope       string
	IsDefault   bool
	UsersCount  int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) ListRoles(ctx context.Context, organizationID uuid.UUID) ([]ListRolesRow, error) {
	rows, err := q.db.Query(ctx, listRoles, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRolesRow
	for rows.Next() {
		var i ListRolesRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.Type,
			&i.Scope,
			&i.IsDefault,
			&i.UsersCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
