// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tags.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countTags = `-- name: CountTags :one
SELECT COUNT(*)
FROM tags
WHERE organization_id = $1
  AND deleted_at IS NULL
`

func (q *Queries) CountTags(ctx context.Context, organizationID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTags, organizationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTag = `-- name: CreateTag :one
INSERT INTO tags (id, organization_id, name, color)
VALUES ($1, $2, $3, $4)
RETURNING id, organization_id, name, color, created_at, updated_at
`

type CreateTagParams struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	Name           string
	Color          string
}

type CreateTagRow struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	Name           string
	Color          string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (CreateTagRow, error) {
	row := q.db.QueryRow(ctx, createTag,
		arg.ID,
		arg.OrganizationID,
		arg.Name,
		arg.Color,
	)
	var i CreateTagRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTagByID = `-- name: GetTagByID :one
SELECT id, organization_id, name, color, created_at, updated_at
FROM tags
WHERE id = $1
  AND organization_id = $2
  AND deleted_at IS NULL
`

type GetTagByIDParams struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
}

type GetTagByIDRow struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	Name           string
	Color          string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

func (q *Queries) GetTagByID(ctx context.Context, arg GetTagByIDParams) (GetTagByIDRow, error) {
	row := q.db.QueryRow(ctx, getTagByID, arg.ID, arg.OrganizationID)
	var i GetTagByIDRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTagByName = `-- name: GetTagByName :one
SELECT id, organization_id, name, color, created_at, updated_at
FROM tags
WHERE organization_id = $1
  AND LOWER(name) = LOWER($2)
  AND deleted_at IS NULL
`

type GetTagByNameParams struct {
	OrganizationID uuid.UUID
	Lower          string
}

type GetTagByNameRow struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	Name           string
	Color          string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

func (q *Queries) GetTagByName(ctx context.Context, arg GetTagByNameParams) (GetTagByNameRow, error) {
	row := q.db.QueryRow(ctx, getTagByName, arg.OrganizationID, arg.Lower)
	var i GetTagByNameRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTags = `-- name: ListTags :many
SELECT t.id, t.organization_id, t.name, t.color, t.created_at, t.updated_at,
       COUNT(m.id) FILTER (WHERE m.deleted_at IS NULL) AS usage_count
FROM tags t
LEFT JOIN mission_tags mt ON mt.org_id = t.organization_id AND mt.tag_id = t.id
LEFT JOIN missions m       ON m.organization_id = mt.org_id AND m.id = mt.mission_id
WHERE t.organization_id = $1
  AND t.deleted_at IS NULL
GROUP BY t.id
ORDER BY LOWER(t.name) ASC
LIMIT $2 OFFSET $3
`

type ListTagsParams struct {
	OrganizationID uuid.UUID
	Limit          int32
	Offset         int32
}

type ListTagsRow struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	Name           string
	Color          string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	UsageCount     int64
}

func (q *Queries) ListTags(ctx context.Context, arg ListTagsParams) ([]ListTagsRow, error) {
	rows, err := q.db.Query(ctx, listTags, arg.OrganizationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTagsRow
	for rows.Next() {
		var i ListTagsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Color,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UsageCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteTag = `-- name: SoftDeleteTag :exec
UPDATE tags
SET deleted_at = NOW()
WHERE id = $1
  AND organization_id = $2
  AND deleted_at IS NULL
`

type SoftDeleteTagParams struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
}

func (q *Queries) SoftDeleteTag(ctx context.Context, arg SoftDeleteTagParams) error {
	_, err := q.db.Exec(ctx, softDeleteTag, arg.ID, arg.OrganizationID)
	return err
}

const updateTag = `-- name: UpdateTag :one
UPDATE tags
SET name       = $3,
    color      = $4,
    updated_at = NOW()
WHERE id = $1
  AND organization_id = $2
  AND deleted_at IS NULL
RETURNING id, organization_id, name, color, created_at, updated_at
`

type UpdateTagParams struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	Name           string
	Color          string
}

type UpdateTagRow struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	Name           string
	Color          string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

func (q *Queries) UpdateTag(ctx context.Context, arg UpdateTagParams) (UpdateTagRow, error) {
	row := q.db.QueryRow(ctx, updateTag,
		arg.ID,
		arg.OrganizationID,
		arg.Name,
		arg.Color,
	)
	var i UpdateTagRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
