// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tasks.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countTasks = `-- name: CountTasks :one
SELECT COUNT(*)
FROM tasks
WHERE organization_id = $1
  AND deleted_at IS NULL
  AND ($2::uuid IS NULL OR mission_id = $2)
  AND ($3::uuid IS NULL OR indicator_id = $3)
  AND ($4::uuid IS NULL OR assignee_id = $4)
  AND ($5::text IS NULL OR status = $5)
`

type CountTasksParams struct {
	OrganizationID uuid.UUID
	MissionID      pgtype.UUID
	IndicatorID    pgtype.UUID
	AssigneeID     pgtype.UUID
	Status         pgtype.Text
}

func (q *Queries) CountTasks(ctx context.Context, arg CountTasksParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTasks,
		arg.OrganizationID,
		arg.MissionID,
		arg.IndicatorID,
		arg.AssigneeID,
		arg.Status,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (id, organization_id, mission_id, indicator_id, assignee_id, title, description, status, due_date, completed_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, organization_id, mission_id, indicator_id, assignee_id, title, description, status, due_date, completed_at, created_at, updated_at
`

type CreateTaskParams struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	MissionID      uuid.UUID
	IndicatorID    pgtype.UUID
	AssigneeID     uuid.UUID
	Title          string
	Description    pgtype.Text
	Status         string
	DueDate        pgtype.Date
	CompletedAt    pgtype.Timestamptz
}

type CreateTaskRow struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	MissionID      uuid.UUID
	IndicatorID    pgtype.UUID
	AssigneeID     uuid.UUID
	Title          string
	Description    pgtype.Text
	Status         string
	DueDate        pgtype.Date
	CompletedAt    pgtype.Timestamptz
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (CreateTaskRow, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.ID,
		arg.OrganizationID,
		arg.MissionID,
		arg.IndicatorID,
		arg.AssigneeID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.DueDate,
		arg.CompletedAt,
	)
	var i CreateTaskRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.MissionID,
		&i.IndicatorID,
		&i.AssigneeID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.DueDate,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTaskByID = `-- name: GetTaskByID :one
SELECT id, organization_id, mission_id, indicator_id, assignee_id, title, description, status, due_date, completed_at, created_at, updated_at
FROM tasks
WHERE id = $1
  AND organization_id = $2
  AND deleted_at IS NULL
`

type GetTaskByIDParams struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
}

type GetTaskByIDRow struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	MissionID      uuid.UUID
	IndicatorID    pgtype.UUID
	AssigneeID     uuid.UUID
	Title          string
	Description    pgtype.Text
	Status         string
	DueDate        pgtype.Date
	CompletedAt    pgtype.Timestamptz
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

func (q *Queries) GetTaskByID(ctx context.Context, arg GetTaskByIDParams) (GetTaskByIDRow, error) {
	row := q.db.QueryRow(ctx, getTaskByID, arg.ID, arg.OrganizationID)
	var i GetTaskByIDRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.MissionID,
		&i.IndicatorID,
		&i.AssigneeID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.DueDate,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTasks = `-- name: ListTasks :many
SELECT id, organization_id, mission_id, indicator_id, assignee_id, title, description, status, due_date, completed_at, created_at, updated_at
FROM tasks
WHERE organization_id = $1
  AND deleted_at IS NULL
  AND ($4::uuid IS NULL OR mission_id = $4)
  AND ($5::uuid IS NULL OR indicator_id = $5)
  AND ($6::uuid IS NULL OR assignee_id = $6)
  AND ($7::text IS NULL OR status = $7)
ORDER BY created_at ASC
LIMIT $2 OFFSET $3
`

type ListTasksParams struct {
	OrganizationID uuid.UUID
	Limit          int32
	Offset         int32
	MissionID      pgtype.UUID
	IndicatorID    pgtype.UUID
	AssigneeID     pgtype.UUID
	Status         pgtype.Text
}

type ListTasksRow struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	MissionID      uuid.UUID
	IndicatorID    pgtype.UUID
	AssigneeID     uuid.UUID
	Title          string
	Description    pgtype.Text
	Status         string
	DueDate        pgtype.Date
	CompletedAt    pgtype.Timestamptz
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

func (q *Queries) ListTasks(ctx context.Context, arg ListTasksParams) ([]ListTasksRow, error) {
	rows, err := q.db.Query(ctx, listTasks,
		arg.OrganizationID,
		arg.Limit,
		arg.Offset,
		arg.MissionID,
		arg.IndicatorID,
		arg.AssigneeID,
		arg.Status,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTasksRow
	for rows.Next() {
		var i ListTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.MissionID,
			&i.IndicatorID,
			&i.AssigneeID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.DueDate,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteTask = `-- name: SoftDeleteTask :execrows
UPDATE tasks
SET deleted_at = NOW()
WHERE id = $1
  AND organization_id = $2
  AND deleted_at IS NULL
`

type SoftDeleteTaskParams struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
}

func (q *Queries) SoftDeleteTask(ctx context.Context, arg SoftDeleteTaskParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteTask, arg.ID, arg.OrganizationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks
SET title        = $3,
    description  = $4,
    indicator_id = $5,
    assignee_id  = $6,
    status       = $7,
    due_date     = $8,
    completed_at = $9,
    updated_at   = NOW()
WHERE id = $1
  AND organization_id = $2
  AND deleted_at IS NULL
RETURNING id, organization_id, mission_id, indicator_id, assignee_id, title, description, status, due_date, completed_at, created_at, updated_at
`

type UpdateTaskParams struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	Title          string
	Description    pgtype.Text
	IndicatorID    pgtype.UUID
	AssigneeID     uuid.UUID
	Status         string
	DueDate        pgtype.Date
	CompletedAt    pgtype.Timestamptz
}

type UpdateTaskRow struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	MissionID      uuid.UUID
	IndicatorID    pgtype.UUID
	AssigneeID     uuid.UUID
	Title          string
	Description    pgtype.Text
	Status         string
	DueDate        pgtype.Date
	CompletedAt    pgtype.Timestamptz
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (UpdateTaskRow, error) {
	row := q.db.QueryRow(ctx, updateTask,
		arg.ID,
		arg.OrganizationID,
		arg.Title,
		arg.Description,
		arg.IndicatorID,
		arg.AssigneeID,
		arg.Status,
		arg.DueDate,
		arg.CompletedAt,
	)
	var i UpdateTaskRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.MissionID,
		&i.IndicatorID,
		&i.AssigneeID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.DueDate,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
