// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: teams.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countTeams = `-- name: CountTeams :one
SELECT COUNT(*)
FROM teams
WHERE organization_id = $1
  AND deleted_at IS NULL
`

func (q *Queries) CountTeams(ctx context.Context, organizationID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTeams, organizationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTeamsByStatus = `-- name: CountTeamsByStatus :one
SELECT COUNT(*)
FROM teams
WHERE organization_id = $1
  AND status = $2
  AND deleted_at IS NULL
`

type CountTeamsByStatusParams struct {
	OrganizationID uuid.UUID
	Status         string
}

func (q *Queries) CountTeamsByStatus(ctx context.Context, arg CountTeamsByStatusParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTeamsByStatus, arg.OrganizationID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTeam = `-- name: CreateTeam :one
INSERT INTO teams (id, organization_id, name, description, color, status)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, organization_id, name, description, color, status, created_at, updated_at
`

type CreateTeamParams struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	Name           string
	Description    pgtype.Text
	Color          string
	Status         string
}

type CreateTeamRow struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	Name           string
	Description    pgtype.Text
	Color          string
	Status         string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (CreateTeamRow, error) {
	row := q.db.QueryRow(ctx, createTeam,
		arg.ID,
		arg.OrganizationID,
		arg.Name,
		arg.Description,
		arg.Color,
		arg.Status,
	)
	var i CreateTeamRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Description,
		&i.Color,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTeamMember = `-- name: CreateTeamMember :one
INSERT INTO team_members (organization_id, team_id, user_id, role_in_team)
VALUES ($1, $2, $3, $4)
RETURNING id, team_id, user_id, role_in_team, joined_at, created_at, updated_at
`

type CreateTeamMemberParams struct {
	OrganizationID uuid.UUID
	TeamID         uuid.UUID
	UserID         uuid.UUID
	RoleInTeam     string
}

type CreateTeamMemberRow struct {
	ID         uuid.UUID
	TeamID     uuid.UUID
	UserID     uuid.UUID
	RoleInTeam string
	JoinedAt   time.Time
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

func (q *Queries) CreateTeamMember(ctx context.Context, arg CreateTeamMemberParams) (CreateTeamMemberRow, error) {
	row := q.db.QueryRow(ctx, createTeamMember,
		arg.OrganizationID,
		arg.TeamID,
		arg.UserID,
		arg.RoleInTeam,
	)
	var i CreateTeamMemberRow
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.UserID,
		&i.RoleInTeam,
		&i.JoinedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTeamByID = `-- name: GetTeamByID :one
SELECT id, organization_id, name, description, color, status, created_at, updated_at
FROM teams
WHERE id = $1
  AND organization_id = $2
  AND deleted_at IS NULL
`

type GetTeamByIDParams struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
}

type GetTeamByIDRow struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	Name           string
	Description    pgtype.Text
	Color          string
	Status         string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

func (q *Queries) GetTeamByID(ctx context.Context, arg GetTeamByIDParams) (GetTeamByIDRow, error) {
	row := q.db.QueryRow(ctx, getTeamByID, arg.ID, arg.OrganizationID)
	var i GetTeamByIDRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Description,
		&i.Color,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTeamByName = `-- name: GetTeamByName :one
SELECT id, organization_id, name, description, color, status, created_at, updated_at
FROM teams
WHERE organization_id = $1
  AND LOWER(name) = LOWER($2)
  AND deleted_at IS NULL
`

type GetTeamByNameParams struct {
	OrganizationID uuid.UUID
	Lower          string
}

type GetTeamByNameRow struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	Name           string
	Description    pgtype.Text
	Color          string
	Status         string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

func (q *Queries) GetTeamByName(ctx context.Context, arg GetTeamByNameParams) (GetTeamByNameRow, error) {
	row := q.db.QueryRow(ctx, getTeamByName, arg.OrganizationID, arg.Lower)
	var i GetTeamByNameRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Description,
		&i.Color,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTeamMemberByTeamAndUser = `-- name: GetTeamMemberByTeamAndUser :one
SELECT id, team_id, user_id, role_in_team, joined_at, created_at, updated_at
FROM team_members
WHERE team_id = $1
  AND user_id = $2
  AND deleted_at IS NULL
`

type GetTeamMemberByTeamAndUserParams struct {
	TeamID uuid.UUID
	UserID uuid.UUID
}

type GetTeamMemberByTeamAndUserRow struct {
	ID         uuid.UUID
	TeamID     uuid.UUID
	UserID     uuid.UUID
	RoleInTeam string
	JoinedAt   time.Time
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

func (q *Queries) GetTeamMemberByTeamAndUser(ctx context.Context, arg GetTeamMemberByTeamAndUserParams) (GetTeamMemberByTeamAndUserRow, error) {
	row := q.db.QueryRow(ctx, getTeamMemberByTeamAndUser, arg.TeamID, arg.UserID)
	var i GetTeamMemberByTeamAndUserRow
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.UserID,
		&i.RoleInTeam,
		&i.JoinedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTeamMembers = `-- name: ListTeamMembers :many
SELECT tm.id,
       tm.team_id,
       tm.user_id,
       tm.role_in_team,
       tm.joined_at,
       tm.created_at,
       tm.updated_at,
       u.first_name,
       u.last_name,
       u.job_title
FROM team_members tm
         INNER JOIN teams t ON t.id = tm.team_id AND t.organization_id = $2 AND t.deleted_at IS NULL
         INNER JOIN organization_memberships om ON om.organization_id = t.organization_id AND om.user_id = tm.user_id AND om.status = 'active' AND om.deleted_at IS NULL
         INNER JOIN users u ON u.id = tm.user_id AND u.deleted_at IS NULL
WHERE tm.team_id = $1
  AND tm.deleted_at IS NULL
ORDER BY tm.created_at ASC
`

type ListTeamMembersParams struct {
	TeamID         uuid.UUID
	OrganizationID uuid.UUID
}

type ListTeamMembersRow struct {
	ID         uuid.UUID
	TeamID     uuid.UUID
	UserID     uuid.UUID
	RoleInTeam string
	JoinedAt   time.Time
	CreatedAt  time.Time
	UpdatedAt  time.Time
	FirstName  string
	LastName   string
	JobTitle   pgtype.Text
}

func (q *Queries) ListTeamMembers(ctx context.Context, arg ListTeamMembersParams) ([]ListTeamMembersRow, error) {
	rows, err := q.db.Query(ctx, listTeamMembers, arg.TeamID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTeamMembersRow
	for rows.Next() {
		var i ListTeamMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.UserID,
			&i.RoleInTeam,
			&i.JoinedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FirstName,
			&i.LastName,
			&i.JobTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamMembersByOrganizationUser = `-- name: ListTeamMembersByOrganizationUser :many
SELECT tm.id, tm.team_id, tm.user_id, tm.role_in_team, tm.joined_at, tm.created_at, tm.updated_at
FROM team_members tm
  JOIN teams t ON t.id = tm.team_id AND t.organization_id = $1 AND t.deleted_at IS NULL
WHERE tm.user_id = $2 AND tm.deleted_at IS NULL
ORDER BY tm.created_at ASC
`

type ListTeamMembersByOrganizationUserParams struct {
	OrganizationID uuid.UUID
	UserID         uuid.UUID
}

type ListTeamMembersByOrganizationUserRow struct {
	ID         uuid.UUID
	TeamID     uuid.UUID
	UserID     uuid.UUID
	RoleInTeam string
	JoinedAt   time.Time
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

func (q *Queries) ListTeamMembersByOrganizationUser(ctx context.Context, arg ListTeamMembersByOrganizationUserParams) ([]ListTeamMembersByOrganizationUserRow, error) {
	rows, err := q.db.Query(ctx, listTeamMembersByOrganizationUser, arg.OrganizationID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTeamMembersByOrganizationUserRow
	for rows.Next() {
		var i ListTeamMembersByOrganizationUserRow
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.UserID,
			&i.RoleInTeam,
			&i.JoinedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamMembersByOrganizationUsers = `-- name: ListTeamMembersByOrganizationUsers :many
SELECT tm.team_id, tm.user_id
FROM team_members tm
  JOIN teams t ON t.id = tm.team_id AND t.organization_id = $1 AND t.deleted_at IS NULL
WHERE tm.user_id = ANY($2::uuid[]) AND tm.deleted_at IS NULL
`

type ListTeamMembersByOrganizationUsersParams struct {
	OrganizationID uuid.UUID
	UserIds        []uuid.UUID
}

type ListTeamMembersByOrganizationUsersRow struct {
	TeamID uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) ListTeamMembersByOrganizationUsers(ctx context.Context, arg ListTeamMembersByOrganizationUsersParams) ([]ListTeamMembersByOrganizationUsersRow, error) {
	rows, err := q.db.Query(ctx, listTeamMembersByOrganizationUsers, arg.OrganizationID, arg.UserIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTeamMembersByOrganizationUsersRow
	for rows.Next() {
		var i ListTeamMembersByOrganizationUsersRow
		if err := rows.Scan(&i.TeamID, &i.UserID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamMembersForSync = `-- name: ListTeamMembersForSync :many
SELECT id, team_id, user_id, role_in_team, joined_at, created_at, updated_at
FROM team_members
WHERE team_id = $1
  AND deleted_at IS NULL
ORDER BY created_at ASC
`

type ListTeamMembersForSyncRow struct {
	ID         uuid.UUID
	TeamID     uuid.UUID
	UserID     uuid.UUID
	RoleInTeam string
	JoinedAt   time.Time
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

func (q *Queries) ListTeamMembersForSync(ctx context.Context, teamID uuid.UUID) ([]ListTeamMembersForSyncRow, error) {
	rows, err := q.db.Query(ctx, listTeamMembersForSync, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTeamMembersForSyncRow
	for rows.Next() {
		var i ListTeamMembersForSyncRow
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.UserID,
			&i.RoleInTeam,
			&i.JoinedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeams = `-- name: ListTeams :many
SELECT id, organization_id, name, description, color, status, created_at, updated_at
FROM teams
WHERE organization_id = $1
  AND deleted_at IS NULL
ORDER BY created_at ASC
LIMIT $2 OFFSET $3
`

type ListTeamsParams struct {
	OrganizationID uuid.UUID
	Limit          int32
	Offset         int32
}

type ListTeamsRow struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	Name           string
	Description    pgtype.Text
	Color          string
	Status         string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

func (q *Queries) ListTeams(ctx context.Context, arg ListTeamsParams) ([]ListTeamsRow, error) {
	rows, err := q.db.Query(ctx, listTeams, arg.OrganizationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTeamsRow
	for rows.Next() {
		var i ListTeamsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Description,
			&i.Color,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamsByStatus = `-- name: ListTeamsByStatus :many
SELECT id, organization_id, name, description, color, status, created_at, updated_at
FROM teams
WHERE organization_id = $1
  AND status = $2
  AND deleted_at IS NULL
ORDER BY created_at ASC
LIMIT $3 OFFSET $4
`

type ListTeamsByStatusParams struct {
	OrganizationID uuid.UUID
	Status         string
	Limit          int32
	Offset         int32
}

type ListTeamsByStatusRow struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	Name           string
	Description    pgtype.Text
	Color          string
	Status         string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

func (q *Queries) ListTeamsByStatus(ctx context.Context, arg ListTeamsByStatusParams) ([]ListTeamsByStatusRow, error) {
	rows, err := q.db.Query(ctx, listTeamsByStatus,
		arg.OrganizationID,
		arg.Status,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTeamsByStatusRow
	for rows.Next() {
		var i ListTeamsByStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Description,
			&i.Color,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteTeam = `-- name: SoftDeleteTeam :exec
UPDATE teams
SET deleted_at = NOW()
WHERE id = $1
  AND organization_id = $2
  AND deleted_at IS NULL
`

type SoftDeleteTeamParams struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
}

func (q *Queries) SoftDeleteTeam(ctx context.Context, arg SoftDeleteTeamParams) error {
	_, err := q.db.Exec(ctx, softDeleteTeam, arg.ID, arg.OrganizationID)
	return err
}

const softDeleteTeamMember = `-- name: SoftDeleteTeamMember :exec
UPDATE team_members
SET deleted_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteTeamMember(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteTeamMember, id)
	return err
}

const softDeleteTeamMembersByOrganizationUser = `-- name: SoftDeleteTeamMembersByOrganizationUser :exec
UPDATE team_members tm
SET deleted_at = NOW()
FROM teams t
WHERE tm.team_id = t.id
  AND t.organization_id = $1
  AND tm.user_id = $2
  AND tm.deleted_at IS NULL
  AND t.deleted_at IS NULL
`

type SoftDeleteTeamMembersByOrganizationUserParams struct {
	OrganizationID uuid.UUID
	UserID         uuid.UUID
}

func (q *Queries) SoftDeleteTeamMembersByOrganizationUser(ctx context.Context, arg SoftDeleteTeamMembersByOrganizationUserParams) error {
	_, err := q.db.Exec(ctx, softDeleteTeamMembersByOrganizationUser, arg.OrganizationID, arg.UserID)
	return err
}

const softDeleteTeamMembersByTeam = `-- name: SoftDeleteTeamMembersByTeam :exec
UPDATE team_members
SET deleted_at = NOW()
WHERE team_id = $1
  AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteTeamMembersByTeam(ctx context.Context, teamID uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteTeamMembersByTeam, teamID)
	return err
}

const updateTeam = `-- name: UpdateTeam :one
UPDATE teams
SET name        = $3,
    description = $4,
    color       = $5,
    status      = $6,
    updated_at  = NOW()
WHERE id = $1
  AND organization_id = $2
  AND deleted_at IS NULL
RETURNING id, organization_id, name, description, color, status, created_at, updated_at
`

type UpdateTeamParams struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	Name           string
	Description    pgtype.Text
	Color          string
	Status         string
}

type UpdateTeamRow struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	Name           string
	Description    pgtype.Text
	Color          string
	Status         string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

func (q *Queries) UpdateTeam(ctx context.Context, arg UpdateTeamParams) (UpdateTeamRow, error) {
	row := q.db.QueryRow(ctx, updateTeam,
		arg.ID,
		arg.OrganizationID,
		arg.Name,
		arg.Description,
		arg.Color,
		arg.Status,
	)
	var i UpdateTeamRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Description,
		&i.Color,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTeamMember = `-- name: UpdateTeamMember :one
UPDATE team_members
SET role_in_team = $2,
    updated_at   = NOW()
WHERE id = $1
  AND deleted_at IS NULL
RETURNING id, team_id, user_id, role_in_team, joined_at, created_at, updated_at
`

type UpdateTeamMemberParams struct {
	ID         uuid.UUID
	RoleInTeam string
}

type UpdateTeamMemberRow struct {
	ID         uuid.UUID
	TeamID     uuid.UUID
	UserID     uuid.UUID
	RoleInTeam string
	JoinedAt   time.Time
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

func (q *Queries) UpdateTeamMember(ctx context.Context, arg UpdateTeamMemberParams) (UpdateTeamMemberRow, error) {
	row := q.db.QueryRow(ctx, updateTeamMember, arg.ID, arg.RoleInTeam)
	var i UpdateTeamMemberRow
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.UserID,
		&i.RoleInTeam,
		&i.JoinedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
