// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countSearchUsers = `-- name: CountSearchUsers :one
SELECT COUNT(*) FROM users
WHERE deleted_at IS NULL
  AND (name ILIKE $1 OR email ILIKE $1)
`

func (q *Queries) CountSearchUsers(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRow(ctx, countSearchUsers, name)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
WHERE deleted_at IS NULL
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersByStatus = `-- name: CountUsersByStatus :one
SELECT COUNT(*) FROM users
WHERE status = $1
  AND deleted_at IS NULL
`

func (q *Queries) CountUsersByStatus(ctx context.Context, status string) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, name, email, password_hash, status, is_system_admin)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, email, password_hash, status, is_system_admin, created_at, updated_at
`

type CreateUserParams struct {
	ID            uuid.UUID
	Name          string
	Email         string
	PasswordHash  string
	Status        string
	IsSystemAdmin bool
}

type CreateUserRow struct {
	ID            uuid.UUID
	Name          string
	Email         string
	PasswordHash  string
	Status        string
	IsSystemAdmin bool
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.PasswordHash,
		arg.Status,
		arg.IsSystemAdmin,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.IsSystemAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, password_hash, status, is_system_admin, created_at, updated_at FROM users
WHERE LOWER(email) = LOWER($1)
  AND deleted_at IS NULL
`

type GetUserByEmailRow struct {
	ID            uuid.UUID
	Name          string
	Email         string
	PasswordHash  string
	Status        string
	IsSystemAdmin bool
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) GetUserByEmail(ctx context.Context, lower string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, lower)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.IsSystemAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, email, password_hash, status, is_system_admin, created_at, updated_at FROM users
WHERE id = $1
  AND deleted_at IS NULL
`

type GetUserByIDRow struct {
	ID            uuid.UUID
	Name          string
	Email         string
	PasswordHash  string
	Status        string
	IsSystemAdmin bool
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.IsSystemAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, name, email, password_hash, status, is_system_admin, created_at, updated_at FROM users
WHERE deleted_at IS NULL
ORDER BY name ASC
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32
	Offset int32
}

type ListUsersRow struct {
	ID            uuid.UUID
	Name          string
	Email         string
	PasswordHash  string
	Status        string
	IsSystemAdmin bool
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.PasswordHash,
			&i.Status,
			&i.IsSystemAdmin,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersByStatus = `-- name: ListUsersByStatus :many
SELECT id, name, email, password_hash, status, is_system_admin, created_at, updated_at FROM users
WHERE status = $1
  AND deleted_at IS NULL
ORDER BY name ASC
LIMIT $2 OFFSET $3
`

type ListUsersByStatusParams struct {
	Status string
	Limit  int32
	Offset int32
}

type ListUsersByStatusRow struct {
	ID            uuid.UUID
	Name          string
	Email         string
	PasswordHash  string
	Status        string
	IsSystemAdmin bool
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) ListUsersByStatus(ctx context.Context, arg ListUsersByStatusParams) ([]ListUsersByStatusRow, error) {
	rows, err := q.db.Query(ctx, listUsersByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersByStatusRow
	for rows.Next() {
		var i ListUsersByStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.PasswordHash,
			&i.Status,
			&i.IsSystemAdmin,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchUsers = `-- name: SearchUsers :many
SELECT id, name, email, password_hash, status, is_system_admin, created_at, updated_at FROM users
WHERE deleted_at IS NULL
  AND (name ILIKE $1 OR email ILIKE $1)
ORDER BY name ASC
LIMIT $2 OFFSET $3
`

type SearchUsersParams struct {
	Name   string
	Limit  int32
	Offset int32
}

type SearchUsersRow struct {
	ID            uuid.UUID
	Name          string
	Email         string
	PasswordHash  string
	Status        string
	IsSystemAdmin bool
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) SearchUsers(ctx context.Context, arg SearchUsersParams) ([]SearchUsersRow, error) {
	rows, err := q.db.Query(ctx, searchUsers, arg.Name, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchUsersRow
	for rows.Next() {
		var i SearchUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.PasswordHash,
			&i.Status,
			&i.IsSystemAdmin,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteUser = `-- name: SoftDeleteUser :exec
UPDATE users
SET deleted_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteUser, id)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET name       = $2,
    email      = $3,
    password_hash = $4,
    status     = $5,
    is_system_admin = $6,
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
RETURNING id, name, email, password_hash, status, is_system_admin, created_at, updated_at
`

type UpdateUserParams struct {
	ID            uuid.UUID
	Name          string
	Email         string
	PasswordHash  string
	Status        string
	IsSystemAdmin bool
}

type UpdateUserRow struct {
	ID            uuid.UUID
	Name          string
	Email         string
	PasswordHash  string
	Status        string
	IsSystemAdmin bool
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.PasswordHash,
		arg.Status,
		arg.IsSystemAdmin,
	)
	var i UpdateUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.IsSystemAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
