// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: users.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, name, email, password_hash, status, is_system_admin)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, email, password_hash, status, is_system_admin, created_at, updated_at
`

type CreateUserParams struct {
	ID            uuid.UUID
	Name          string
	Email         string
	PasswordHash  string
	Status        string
	IsSystemAdmin bool
}

type CreateUserRow struct {
	ID            uuid.UUID
	Name          string
	Email         string
	PasswordHash  string
	Status        string
	IsSystemAdmin bool
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.PasswordHash,
		arg.Status,
		arg.IsSystemAdmin,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.IsSystemAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, password_hash, status, is_system_admin, created_at, updated_at FROM users
WHERE LOWER(email) = LOWER($1)
  AND deleted_at IS NULL
`

type GetUserByEmailRow struct {
	ID            uuid.UUID
	Name          string
	Email         string
	PasswordHash  string
	Status        string
	IsSystemAdmin bool
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) GetUserByEmail(ctx context.Context, lower string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, lower)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.IsSystemAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, email, password_hash, status, is_system_admin, created_at, updated_at FROM users
WHERE id = $1
  AND deleted_at IS NULL
`

type GetUserByIDRow struct {
	ID            uuid.UUID
	Name          string
	Email         string
	PasswordHash  string
	Status        string
	IsSystemAdmin bool
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.IsSystemAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET name       = $2,
    email      = $3,
    password_hash = $4,
    status     = $5,
    is_system_admin = $6,
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
RETURNING id, name, email, password_hash, status, is_system_admin, created_at, updated_at
`

type UpdateUserParams struct {
	ID            uuid.UUID
	Name          string
	Email         string
	PasswordHash  string
	Status        string
	IsSystemAdmin bool
}

type UpdateUserRow struct {
	ID            uuid.UUID
	Name          string
	Email         string
	PasswordHash  string
	Status        string
	IsSystemAdmin bool
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.PasswordHash,
		arg.Status,
		arg.IsSystemAdmin,
	)
	var i UpdateUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.IsSystemAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
