// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: users.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countOrganizationUsers = `-- name: CountOrganizationUsers :one
SELECT COUNT(*)
FROM users u
INNER JOIN organization_memberships om ON om.user_id = u.id
WHERE om.organization_id = $1
  AND om.deleted_at IS NULL
  AND u.deleted_at IS NULL
`

func (q *Queries) CountOrganizationUsers(ctx context.Context, organizationID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOrganizationUsers, organizationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOrganizationUsersByStatus = `-- name: CountOrganizationUsersByStatus :one
SELECT COUNT(*)
FROM users u
INNER JOIN organization_memberships om ON om.user_id = u.id
WHERE om.organization_id = $1
  AND u.status = $2
  AND om.deleted_at IS NULL
  AND u.deleted_at IS NULL
`

type CountOrganizationUsersByStatusParams struct {
	OrganizationID uuid.UUID
	Status         string
}

func (q *Queries) CountOrganizationUsersByStatus(ctx context.Context, arg CountOrganizationUsersByStatusParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOrganizationUsersByStatus, arg.OrganizationID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, first_name, last_name, email, password_hash, status, is_system_admin,
                   nickname, job_title, birth_date, language, gender, phone)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, first_name, last_name, email, password_hash, status, is_system_admin,
          nickname, job_title, birth_date, language, gender, phone, created_at, updated_at
`

type CreateUserParams struct {
	ID            uuid.UUID
	FirstName     string
	LastName      string
	Email         string
	PasswordHash  string
	Status        string
	IsSystemAdmin bool
	Nickname      pgtype.Text
	JobTitle      pgtype.Text
	BirthDate     pgtype.Date
	Language      string
	Gender        pgtype.Text
	Phone         pgtype.Text
}

type CreateUserRow struct {
	ID            uuid.UUID
	FirstName     string
	LastName      string
	Email         string
	PasswordHash  string
	Status        string
	IsSystemAdmin bool
	Nickname      pgtype.Text
	JobTitle      pgtype.Text
	BirthDate     pgtype.Date
	Language      string
	Gender        pgtype.Text
	Phone         pgtype.Text
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.PasswordHash,
		arg.Status,
		arg.IsSystemAdmin,
		arg.Nickname,
		arg.JobTitle,
		arg.BirthDate,
		arg.Language,
		arg.Gender,
		arg.Phone,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.IsSystemAdmin,
		&i.Nickname,
		&i.JobTitle,
		&i.BirthDate,
		&i.Language,
		&i.Gender,
		&i.Phone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, first_name, last_name, email, password_hash, status, is_system_admin,
       nickname, job_title, birth_date, language, gender, phone, created_at, updated_at
FROM users
WHERE LOWER(email) = LOWER($1)
  AND deleted_at IS NULL
`

type GetUserByEmailRow struct {
	ID            uuid.UUID
	FirstName     string
	LastName      string
	Email         string
	PasswordHash  string
	Status        string
	IsSystemAdmin bool
	Nickname      pgtype.Text
	JobTitle      pgtype.Text
	BirthDate     pgtype.Date
	Language      string
	Gender        pgtype.Text
	Phone         pgtype.Text
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) GetUserByEmail(ctx context.Context, lower string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, lower)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.IsSystemAdmin,
		&i.Nickname,
		&i.JobTitle,
		&i.BirthDate,
		&i.Language,
		&i.Gender,
		&i.Phone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, first_name, last_name, email, password_hash, status, is_system_admin,
       nickname, job_title, birth_date, language, gender, phone, created_at, updated_at
FROM users
WHERE id = $1
  AND deleted_at IS NULL
`

type GetUserByIDRow struct {
	ID            uuid.UUID
	FirstName     string
	LastName      string
	Email         string
	PasswordHash  string
	Status        string
	IsSystemAdmin bool
	Nickname      pgtype.Text
	JobTitle      pgtype.Text
	BirthDate     pgtype.Date
	Language      string
	Gender        pgtype.Text
	Phone         pgtype.Text
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.IsSystemAdmin,
		&i.Nickname,
		&i.JobTitle,
		&i.BirthDate,
		&i.Language,
		&i.Gender,
		&i.Phone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOrganizationUsers = `-- name: ListOrganizationUsers :many
SELECT u.id, u.first_name, u.last_name, u.email, u.password_hash, u.status, u.is_system_admin,
       u.nickname, u.job_title, u.birth_date, u.language, u.gender, u.phone, u.created_at, u.updated_at,
       om.role as membership_role, om.status as membership_status
FROM users u
INNER JOIN organization_memberships om ON om.user_id = u.id
WHERE om.organization_id = $1
  AND om.deleted_at IS NULL
  AND u.deleted_at IS NULL
ORDER BY u.created_at ASC
LIMIT $2 OFFSET $3
`

type ListOrganizationUsersParams struct {
	OrganizationID uuid.UUID
	Limit          int32
	Offset         int32
}

type ListOrganizationUsersRow struct {
	ID               uuid.UUID
	FirstName        string
	LastName         string
	Email            string
	PasswordHash     string
	Status           string
	IsSystemAdmin    bool
	Nickname         pgtype.Text
	JobTitle         pgtype.Text
	BirthDate        pgtype.Date
	Language         string
	Gender           pgtype.Text
	Phone            pgtype.Text
	CreatedAt        time.Time
	UpdatedAt        time.Time
	MembershipRole   string
	MembershipStatus string
}

func (q *Queries) ListOrganizationUsers(ctx context.Context, arg ListOrganizationUsersParams) ([]ListOrganizationUsersRow, error) {
	rows, err := q.db.Query(ctx, listOrganizationUsers, arg.OrganizationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrganizationUsersRow
	for rows.Next() {
		var i ListOrganizationUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.PasswordHash,
			&i.Status,
			&i.IsSystemAdmin,
			&i.Nickname,
			&i.JobTitle,
			&i.BirthDate,
			&i.Language,
			&i.Gender,
			&i.Phone,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MembershipRole,
			&i.MembershipStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizationUsersByStatus = `-- name: ListOrganizationUsersByStatus :many
SELECT u.id, u.first_name, u.last_name, u.email, u.password_hash, u.status, u.is_system_admin,
       u.nickname, u.job_title, u.birth_date, u.language, u.gender, u.phone, u.created_at, u.updated_at,
       om.role as membership_role, om.status as membership_status
FROM users u
INNER JOIN organization_memberships om ON om.user_id = u.id
WHERE om.organization_id = $1
  AND u.status = $2
  AND om.deleted_at IS NULL
  AND u.deleted_at IS NULL
ORDER BY u.created_at ASC
LIMIT $3 OFFSET $4
`

type ListOrganizationUsersByStatusParams struct {
	OrganizationID uuid.UUID
	Status         string
	Limit          int32
	Offset         int32
}

type ListOrganizationUsersByStatusRow struct {
	ID               uuid.UUID
	FirstName        string
	LastName         string
	Email            string
	PasswordHash     string
	Status           string
	IsSystemAdmin    bool
	Nickname         pgtype.Text
	JobTitle         pgtype.Text
	BirthDate        pgtype.Date
	Language         string
	Gender           pgtype.Text
	Phone            pgtype.Text
	CreatedAt        time.Time
	UpdatedAt        time.Time
	MembershipRole   string
	MembershipStatus string
}

func (q *Queries) ListOrganizationUsersByStatus(ctx context.Context, arg ListOrganizationUsersByStatusParams) ([]ListOrganizationUsersByStatusRow, error) {
	rows, err := q.db.Query(ctx, listOrganizationUsersByStatus,
		arg.OrganizationID,
		arg.Status,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrganizationUsersByStatusRow
	for rows.Next() {
		var i ListOrganizationUsersByStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.PasswordHash,
			&i.Status,
			&i.IsSystemAdmin,
			&i.Nickname,
			&i.JobTitle,
			&i.BirthDate,
			&i.Language,
			&i.Gender,
			&i.Phone,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MembershipRole,
			&i.MembershipStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET first_name     = $2,
    last_name      = $3,
    email          = $4,
    password_hash  = $5,
    status         = $6,
    is_system_admin = $7,
    nickname       = $8,
    job_title      = $9,
    birth_date     = $10,
    language       = $11,
    gender         = $12,
    phone          = $13,
    updated_at     = NOW()
WHERE id = $1
  AND deleted_at IS NULL
RETURNING id, first_name, last_name, email, password_hash, status, is_system_admin,
          nickname, job_title, birth_date, language, gender, phone, created_at, updated_at
`

type UpdateUserParams struct {
	ID            uuid.UUID
	FirstName     string
	LastName      string
	Email         string
	PasswordHash  string
	Status        string
	IsSystemAdmin bool
	Nickname      pgtype.Text
	JobTitle      pgtype.Text
	BirthDate     pgtype.Date
	Language      string
	Gender        pgtype.Text
	Phone         pgtype.Text
}

type UpdateUserRow struct {
	ID            uuid.UUID
	FirstName     string
	LastName      string
	Email         string
	PasswordHash  string
	Status        string
	IsSystemAdmin bool
	Nickname      pgtype.Text
	JobTitle      pgtype.Text
	BirthDate     pgtype.Date
	Language      string
	Gender        pgtype.Text
	Phone         pgtype.Text
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.PasswordHash,
		arg.Status,
		arg.IsSystemAdmin,
		arg.Nickname,
		arg.JobTitle,
		arg.BirthDate,
		arg.Language,
		arg.Gender,
		arg.Phone,
	)
	var i UpdateUserRow
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.IsSystemAdmin,
		&i.Nickname,
		&i.JobTitle,
		&i.BirthDate,
		&i.Language,
		&i.Gender,
		&i.Phone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
