/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness probe */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description Authenticated session */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthResponse"];
                    };
                };
                /** @description Invalid credentials */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetail"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh access token */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RefreshRequest"];
                };
            };
            responses: {
                /** @description New token pair issued */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthResponse"];
                    };
                };
                /** @description Refresh token invalid, expired or revoked */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetail"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current session */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current authenticated session */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SessionResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetail"];
                    };
                };
            };
        };
        /** Update active organization in session */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateSessionRequest"];
                };
            };
            responses: {
                /** @description Updated authenticated session */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bootstrap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Initial platform bootstrap */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["BootstrapRequest"];
                };
            };
            responses: {
                /** @description Bootstrap completed */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BootstrapResponse"];
                    };
                };
                /** @description Already bootstrapped */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetail"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List organizations
         * @description Returns all accessible organizations for the authenticated user. System admins receive all organizations.
         */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    size?: number;
                    status?: "active" | "inactive";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OrganizationListResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetail"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create organization
         * @description Creates a new organization. Restricted to system admins.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateOrganizationRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Organization"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetail"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetail"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /**
         * Get organization
         * @description Returns the organization only if it is accessible to the authenticated user. Inaccessible organizations return 404. System admins may access any organization.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Organization"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetail"];
                    };
                };
                /** @description Not found or inaccessible */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetail"];
                    };
                };
            };
        };
        /**
         * Update organization
         * @description Updates the organization only if it is accessible to the authenticated user. Inaccessible organizations return 404. System admins may update any organization.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateOrganizationRequest"];
                };
            };
            responses: {
                /** @description Updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Organization"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetail"];
                    };
                };
                /** @description Not found or inaccessible */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetail"];
                    };
                };
                /** @description Domain or workspace conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetail"];
                    };
                };
                /** @description Validation error */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetail"];
                    };
                };
            };
        };
        post?: never;
        /**
         * Soft delete organization
         * @description Soft deletes an organization and its memberships. Restricted to system admins.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetail"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetail"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetail"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List users from active organization */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    size?: number;
                    status?: "active" | "inactive";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserListResponse"];
                    };
                };
            };
        };
        put?: never;
        /** Create user in active organization */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateUserRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Get user from active organization */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
            };
        };
        /** Update user in active organization */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateUserRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
            };
        };
        post?: never;
        /**
         * Soft delete membership from active organization
         * @description Soft deletes the user's membership in the active organization.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetail"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetail"];
                    };
                };
                /** @description Not found or inaccessible */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetail"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}/membership": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Get user membership in active organization */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Membership"];
                    };
                };
            };
        };
        /** Update user membership in active organization */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateMembershipRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Membership"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ProblemDetail: {
            type?: string;
            title: string;
            status: number;
            detail?: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        UpdateSessionRequest: {
            /** Format: uuid */
            organization_id: string;
        };
        SessionUser: {
            /** Format: uuid */
            id: string;
            first_name: string;
            last_name: string;
            /** Format: email */
            email: string;
            /** @enum {string} */
            status: "active" | "inactive";
            is_system_admin: boolean;
        };
        AccessibleOrganization: {
            /** Format: uuid */
            id: string;
            name: string;
            domain: string;
            workspace: string;
            /** @enum {string} */
            status: "active" | "inactive";
            /** @enum {string} */
            membership_role?: "super-admin" | "admin-rh" | "gestor" | "colaborador" | "visualizador";
            /** @enum {string} */
            membership_status?: "invited" | "active" | "inactive";
        };
        SessionResponse: {
            user: components["schemas"]["SessionUser"];
            active_organization?: components["schemas"]["AccessibleOrganization"];
            organizations: components["schemas"]["AccessibleOrganization"][];
        };
        RefreshRequest: {
            refresh_token: string;
        };
        AuthResponse: components["schemas"]["SessionResponse"] & {
            access_token: string;
            refresh_token?: string;
            /** @example Bearer */
            token_type: string;
        };
        BootstrapRequest: {
            organization_name: string;
            /** Format: hostname */
            organization_domain: string;
            organization_workspace: string;
            admin_first_name: string;
            admin_last_name: string;
            /** Format: email */
            admin_email: string;
            admin_password: string;
        };
        BootstrapResponse: {
            access_token: string;
            token_type: string;
            organization: {
                /** Format: uuid */
                id: string;
                name: string;
                domain: string;
                workspace: string;
            };
            admin: {
                /** Format: uuid */
                id: string;
                first_name: string;
                last_name: string;
                /** Format: email */
                email: string;
                is_system_admin: boolean;
            };
        };
        Organization: {
            /** Format: uuid */
            id: string;
            name: string;
            domain: string;
            workspace: string;
            /** @enum {string} */
            status: "active" | "inactive";
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        OrganizationListResponse: {
            data: components["schemas"]["Organization"][];
            total: number;
            page: number;
            size: number;
        };
        CreateOrganizationRequest: {
            name: string;
            /** Format: hostname */
            domain: string;
            workspace: string;
            /** @enum {string} */
            status?: "active" | "inactive";
        };
        UpdateOrganizationRequest: {
            name: string;
            /** Format: hostname */
            domain: string;
            workspace: string;
            /** @enum {string} */
            status: "active" | "inactive";
        };
        User: {
            /** Format: uuid */
            id: string;
            first_name: string;
            last_name: string;
            /** Format: email */
            email: string;
            /** @enum {string} */
            status: "active" | "inactive";
            is_system_admin: boolean;
            nickname?: string;
            job_title?: string;
            /** Format: date */
            birth_date?: string;
            language: string;
            /** @enum {string} */
            gender?: "feminino" | "masculino" | "nao-binario" | "prefiro-nao-dizer";
            phone?: string;
            /** @enum {string} */
            role?: "super-admin" | "admin-rh" | "gestor" | "colaborador" | "visualizador";
            /** @enum {string} */
            membership_status?: "invited" | "active" | "inactive";
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        Membership: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            organization_id: string;
            /** Format: uuid */
            user_id: string;
            /** @enum {string} */
            role: "super-admin" | "admin-rh" | "gestor" | "colaborador" | "visualizador";
            /** @enum {string} */
            status: "invited" | "active" | "inactive";
            /** Format: uuid */
            invited_by_user_id?: string;
            /** Format: date-time */
            joined_at?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        UserListResponse: {
            data: components["schemas"]["User"][];
            total: number;
            page: number;
            size: number;
        };
        CreateUserRequest: {
            first_name: string;
            last_name: string;
            /** Format: email */
            email: string;
            password: string;
            /** @enum {string} */
            role: "super-admin" | "admin-rh" | "gestor" | "colaborador" | "visualizador";
            nickname?: string;
            job_title?: string;
            /** Format: date */
            birth_date?: string;
            language?: string;
            /** @enum {string} */
            gender?: "feminino" | "masculino" | "nao-binario" | "prefiro-nao-dizer";
            phone?: string;
        };
        UpdateUserRequest: {
            first_name: string;
            last_name: string;
            /** Format: email */
            email: string;
            /** @enum {string} */
            status: "active" | "inactive";
            nickname?: string;
            job_title?: string;
            /** Format: date */
            birth_date?: string;
            language?: string;
            /** @enum {string} */
            gender?: "feminino" | "masculino" | "nao-binario" | "prefiro-nao-dizer";
            phone?: string;
        };
        UpdateMembershipRequest: {
            /** @enum {string} */
            role: "super-admin" | "admin-rh" | "gestor" | "colaborador" | "visualizador";
            /** @enum {string} */
            status: "invited" | "active" | "inactive";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
